// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entity.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "light-up-backend/common/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EducationQualificationRequest struct {
	EducationQualification *proto1.EducationQualification `protobuf:"bytes,1,opt,name=educationQualification,proto3" json:"educationQualification,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                       `json:"-"`
	XXX_unrecognized       []byte                         `json:"-"`
	XXX_sizecache          int32                          `json:"-"`
}

func (m *EducationQualificationRequest) Reset()         { *m = EducationQualificationRequest{} }
func (m *EducationQualificationRequest) String() string { return proto.CompactTextString(m) }
func (*EducationQualificationRequest) ProtoMessage()    {}
func (*EducationQualificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{0}
}

func (m *EducationQualificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EducationQualificationRequest.Unmarshal(m, b)
}
func (m *EducationQualificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EducationQualificationRequest.Marshal(b, m, deterministic)
}
func (m *EducationQualificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EducationQualificationRequest.Merge(m, src)
}
func (m *EducationQualificationRequest) XXX_Size() int {
	return xxx_messageInfo_EducationQualificationRequest.Size(m)
}
func (m *EducationQualificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EducationQualificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EducationQualificationRequest proto.InternalMessageInfo

func (m *EducationQualificationRequest) GetEducationQualification() *proto1.EducationQualification {
	if m != nil {
		return m.EducationQualification
	}
	return nil
}

type EducationQualificationResponse struct {
	EducationQualification  *proto1.EducationQualification   `protobuf:"bytes,1,opt,name=educationQualification,proto3" json:"educationQualification,omitempty"`
	EducationQualifications []*proto1.EducationQualification `protobuf:"bytes,2,rep,name=educationQualifications,proto3" json:"educationQualifications,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                         `json:"-"`
	XXX_unrecognized        []byte                           `json:"-"`
	XXX_sizecache           int32                            `json:"-"`
}

func (m *EducationQualificationResponse) Reset()         { *m = EducationQualificationResponse{} }
func (m *EducationQualificationResponse) String() string { return proto.CompactTextString(m) }
func (*EducationQualificationResponse) ProtoMessage()    {}
func (*EducationQualificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{1}
}

func (m *EducationQualificationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EducationQualificationResponse.Unmarshal(m, b)
}
func (m *EducationQualificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EducationQualificationResponse.Marshal(b, m, deterministic)
}
func (m *EducationQualificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EducationQualificationResponse.Merge(m, src)
}
func (m *EducationQualificationResponse) XXX_Size() int {
	return xxx_messageInfo_EducationQualificationResponse.Size(m)
}
func (m *EducationQualificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EducationQualificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EducationQualificationResponse proto.InternalMessageInfo

func (m *EducationQualificationResponse) GetEducationQualification() *proto1.EducationQualification {
	if m != nil {
		return m.EducationQualification
	}
	return nil
}

func (m *EducationQualificationResponse) GetEducationQualifications() []*proto1.EducationQualification {
	if m != nil {
		return m.EducationQualifications
	}
	return nil
}

type OccupationRequest struct {
	Occupation           *proto1.Occupation `protobuf:"bytes,1,opt,name=occupation,proto3" json:"occupation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *OccupationRequest) Reset()         { *m = OccupationRequest{} }
func (m *OccupationRequest) String() string { return proto.CompactTextString(m) }
func (*OccupationRequest) ProtoMessage()    {}
func (*OccupationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{2}
}

func (m *OccupationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OccupationRequest.Unmarshal(m, b)
}
func (m *OccupationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OccupationRequest.Marshal(b, m, deterministic)
}
func (m *OccupationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OccupationRequest.Merge(m, src)
}
func (m *OccupationRequest) XXX_Size() int {
	return xxx_messageInfo_OccupationRequest.Size(m)
}
func (m *OccupationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OccupationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OccupationRequest proto.InternalMessageInfo

func (m *OccupationRequest) GetOccupation() *proto1.Occupation {
	if m != nil {
		return m.Occupation
	}
	return nil
}

type OccupationResponse struct {
	Occupation           *proto1.Occupation   `protobuf:"bytes,1,opt,name=occupation,proto3" json:"occupation,omitempty"`
	Occupations          []*proto1.Occupation `protobuf:"bytes,2,rep,name=occupations,proto3" json:"occupations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OccupationResponse) Reset()         { *m = OccupationResponse{} }
func (m *OccupationResponse) String() string { return proto.CompactTextString(m) }
func (*OccupationResponse) ProtoMessage()    {}
func (*OccupationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{3}
}

func (m *OccupationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OccupationResponse.Unmarshal(m, b)
}
func (m *OccupationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OccupationResponse.Marshal(b, m, deterministic)
}
func (m *OccupationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OccupationResponse.Merge(m, src)
}
func (m *OccupationResponse) XXX_Size() int {
	return xxx_messageInfo_OccupationResponse.Size(m)
}
func (m *OccupationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OccupationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OccupationResponse proto.InternalMessageInfo

func (m *OccupationResponse) GetOccupation() *proto1.Occupation {
	if m != nil {
		return m.Occupation
	}
	return nil
}

func (m *OccupationResponse) GetOccupations() []*proto1.Occupation {
	if m != nil {
		return m.Occupations
	}
	return nil
}

type InstituteRequest struct {
	Institute            *proto1.Institute `protobuf:"bytes,1,opt,name=institute,proto3" json:"institute,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InstituteRequest) Reset()         { *m = InstituteRequest{} }
func (m *InstituteRequest) String() string { return proto.CompactTextString(m) }
func (*InstituteRequest) ProtoMessage()    {}
func (*InstituteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{4}
}

func (m *InstituteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstituteRequest.Unmarshal(m, b)
}
func (m *InstituteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstituteRequest.Marshal(b, m, deterministic)
}
func (m *InstituteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstituteRequest.Merge(m, src)
}
func (m *InstituteRequest) XXX_Size() int {
	return xxx_messageInfo_InstituteRequest.Size(m)
}
func (m *InstituteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstituteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstituteRequest proto.InternalMessageInfo

func (m *InstituteRequest) GetInstitute() *proto1.Institute {
	if m != nil {
		return m.Institute
	}
	return nil
}

type InstituteResponse struct {
	Institute            *proto1.Institute   `protobuf:"bytes,1,opt,name=institute,proto3" json:"institute,omitempty"`
	Institutes           []*proto1.Institute `protobuf:"bytes,2,rep,name=institutes,proto3" json:"institutes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *InstituteResponse) Reset()         { *m = InstituteResponse{} }
func (m *InstituteResponse) String() string { return proto.CompactTextString(m) }
func (*InstituteResponse) ProtoMessage()    {}
func (*InstituteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{5}
}

func (m *InstituteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstituteResponse.Unmarshal(m, b)
}
func (m *InstituteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstituteResponse.Marshal(b, m, deterministic)
}
func (m *InstituteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstituteResponse.Merge(m, src)
}
func (m *InstituteResponse) XXX_Size() int {
	return xxx_messageInfo_InstituteResponse.Size(m)
}
func (m *InstituteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstituteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstituteResponse proto.InternalMessageInfo

func (m *InstituteResponse) GetInstitute() *proto1.Institute {
	if m != nil {
		return m.Institute
	}
	return nil
}

func (m *InstituteResponse) GetInstitutes() []*proto1.Institute {
	if m != nil {
		return m.Institutes
	}
	return nil
}

func init() {
	proto.RegisterType((*EducationQualificationRequest)(nil), "proto.EducationQualificationRequest")
	proto.RegisterType((*EducationQualificationResponse)(nil), "proto.EducationQualificationResponse")
	proto.RegisterType((*OccupationRequest)(nil), "proto.OccupationRequest")
	proto.RegisterType((*OccupationResponse)(nil), "proto.OccupationResponse")
	proto.RegisterType((*InstituteRequest)(nil), "proto.InstituteRequest")
	proto.RegisterType((*InstituteResponse)(nil), "proto.InstituteResponse")
}

func init() { proto.RegisterFile("entity.proto", fileDescriptor_cf50d946d740d100) }

var fileDescriptor_cf50d946d740d100 = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xdf, 0x4e, 0xe2, 0x40,
	0x14, 0xc6, 0x97, 0xdd, 0xb0, 0xc9, 0x1e, 0x4a, 0x42, 0xe7, 0x62, 0x29, 0x24, 0x6c, 0x48, 0xb3,
	0x44, 0x6f, 0x00, 0x85, 0x5b, 0x63, 0x6c, 0x0d, 0x10, 0xae, 0x8c, 0x1a, 0x35, 0xe1, 0x0e, 0x3a,
	0xa3, 0x8e, 0x0e, 0x6d, 0xa5, 0x53, 0x12, 0x12, 0x1f, 0xce, 0x47, 0xf0, 0x91, 0x4c, 0xda, 0xe9,
	0xb4, 0xd2, 0x3f, 0xc8, 0x85, 0x57, 0xcd, 0xcc, 0xf9, 0xbe, 0xdf, 0x39, 0x5f, 0x7b, 0x52, 0x50,
	0x88, 0xcd, 0x29, 0xdf, 0xf4, 0xdc, 0x95, 0xc3, 0x1d, 0x54, 0x0e, 0x1e, 0x4d, 0xc5, 0x72, 0x96,
	0x4b, 0xc7, 0x0e, 0x2f, 0xf5, 0x35, 0xb4, 0x46, 0xd8, 0xb7, 0xe6, 0x9c, 0x3a, 0xf6, 0xa5, 0x3f,
	0x67, 0xf4, 0x9e, 0x86, 0x87, 0x2b, 0xf2, 0xe2, 0x13, 0x8f, 0xa3, 0x1b, 0xf8, 0x4b, 0x32, 0x05,
	0x5a, 0xa9, 0x5d, 0x3a, 0xac, 0x0c, 0x5a, 0x21, 0xa8, 0x97, 0x43, 0xc9, 0x31, 0xeb, 0xef, 0x25,
	0xf8, 0x97, 0xd7, 0xd8, 0x73, 0x1d, 0xdb, 0x23, 0xdf, 0xd4, 0x19, 0xdd, 0x41, 0x3d, 0xbb, 0xe2,
	0x69, 0x3f, 0xdb, 0xbf, 0x76, 0x73, 0xf3, 0xdc, 0xfa, 0x18, 0xd4, 0x0b, 0xcb, 0xf2, 0xdd, 0x4f,
	0xaf, 0xef, 0x18, 0xc0, 0x91, 0x97, 0x62, 0x70, 0x55, 0x34, 0x48, 0xa8, 0x13, 0x22, 0xfd, 0x15,
	0x50, 0x92, 0x23, 0xde, 0xc6, 0xfe, 0x20, 0x34, 0x84, 0x4a, 0x7c, 0x8a, 0xd2, 0x65, 0x78, 0x92,
	0x2a, 0xdd, 0x84, 0xda, 0xd4, 0xf6, 0x38, 0xe5, 0x3e, 0x27, 0x51, 0x88, 0x1e, 0xfc, 0xa1, 0xd1,
	0x9d, 0x68, 0x5d, 0x13, 0x98, 0x58, 0x1b, 0x4b, 0x74, 0x1f, 0xd4, 0x04, 0x43, 0x04, 0xd8, 0x13,
	0x82, 0x8e, 0x00, 0xe4, 0x21, 0x1a, 0x3e, 0x6d, 0x48, 0x68, 0x06, 0x6f, 0x65, 0xa8, 0x8e, 0x82,
	0x8d, 0xbf, 0x26, 0xab, 0x35, 0xb5, 0x08, 0x7a, 0x82, 0x86, 0x81, 0x71, 0xf6, 0x87, 0x44, 0xff,
	0x8b, 0xbf, 0x73, 0x98, 0xbd, 0xd9, 0xd9, 0xa1, 0x0a, 0xd3, 0xe9, 0x3f, 0xd0, 0x0c, 0x5a, 0x13,
	0xc2, 0xb3, 0x65, 0xe6, 0x66, 0x8a, 0x91, 0x1c, 0x1e, 0xef, 0xcd, 0xbe, 0x0d, 0xd8, 0x06, 0x63,
	0xd9, 0x4a, 0x0f, 0x29, 0x11, 0x69, 0xe9, 0xf2, 0xcd, 0xd7, 0xb9, 0x63, 0xa8, 0x1a, 0x18, 0xc7,
	0xab, 0x80, 0xb4, 0xf4, 0x76, 0x88, 0x59, 0x1b, 0x19, 0x15, 0xc9, 0x31, 0x41, 0x9d, 0x10, 0x1e,
	0x97, 0x72, 0xf2, 0x16, 0x32, 0x4e, 0x03, 0x86, 0xc1, 0x58, 0x5c, 0xdd, 0xce, 0x55, 0xe8, 0x3f,
	0x07, 0xc5, 0xc0, 0x58, 0x6e, 0x06, 0xaa, 0xa7, 0x76, 0x45, 0x4c, 0xa1, 0xa5, 0x0b, 0x12, 0x72,
	0x06, 0xb5, 0x09, 0xe1, 0xb2, 0x92, 0x93, 0xa3, 0x88, 0x70, 0x12, 0x10, 0x0c, 0xc6, 0x64, 0x71,
	0x3b, 0x45, 0x81, 0xdb, 0x3c, 0x98, 0x75, 0x18, 0x7d, 0x78, 0xe4, 0x5d, 0xdf, 0xed, 0x2e, 0xe6,
	0xd6, 0x33, 0xb1, 0x71, 0x3f, 0xfc, 0x89, 0x77, 0xbd, 0x70, 0xa7, 0xfb, 0x81, 0x79, 0xf1, 0x3b,
	0x78, 0x0c, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xf1, 0x0c, 0x80, 0xe3, 0x05, 0x00, 0x00,
}
