// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	proto1 "light-up-backend/common/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Admin struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 *proto1.User         `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	LastLogin            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=lastLogin,proto3" json:"lastLogin,omitempty"`
	ModifiedOn           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=modifiedOn,proto3" json:"modifiedOn,omitempty"`
	CreatedOn            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	IsSuper              bool                 `protobuf:"varint,6,opt,name=isSuper,proto3" json:"isSuper,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Admin) Reset()         { *m = Admin{} }
func (m *Admin) String() string { return proto.CompactTextString(m) }
func (*Admin) ProtoMessage()    {}
func (*Admin) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{0}
}

func (m *Admin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Admin.Unmarshal(m, b)
}
func (m *Admin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Admin.Marshal(b, m, deterministic)
}
func (m *Admin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Admin.Merge(m, src)
}
func (m *Admin) XXX_Size() int {
	return xxx_messageInfo_Admin.Size(m)
}
func (m *Admin) XXX_DiscardUnknown() {
	xxx_messageInfo_Admin.DiscardUnknown(m)
}

var xxx_messageInfo_Admin proto.InternalMessageInfo

func (m *Admin) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Admin) GetUser() *proto1.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Admin) GetLastLogin() *timestamp.Timestamp {
	if m != nil {
		return m.LastLogin
	}
	return nil
}

func (m *Admin) GetModifiedOn() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedOn
	}
	return nil
}

func (m *Admin) GetCreatedOn() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedOn
	}
	return nil
}

func (m *Admin) GetIsSuper() bool {
	if m != nil {
		return m.IsSuper
	}
	return false
}

type AdminRequest struct {
	Admin                *Admin   `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminRequest) Reset()         { *m = AdminRequest{} }
func (m *AdminRequest) String() string { return proto.CompactTextString(m) }
func (*AdminRequest) ProtoMessage()    {}
func (*AdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{1}
}

func (m *AdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminRequest.Unmarshal(m, b)
}
func (m *AdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminRequest.Marshal(b, m, deterministic)
}
func (m *AdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminRequest.Merge(m, src)
}
func (m *AdminRequest) XXX_Size() int {
	return xxx_messageInfo_AdminRequest.Size(m)
}
func (m *AdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminRequest proto.InternalMessageInfo

func (m *AdminRequest) GetAdmin() *Admin {
	if m != nil {
		return m.Admin
	}
	return nil
}

type AdminResponse struct {
	Admin                *Admin   `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	Admins               []*Admin `protobuf:"bytes,2,rep,name=admins,proto3" json:"admins,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminResponse) Reset()         { *m = AdminResponse{} }
func (m *AdminResponse) String() string { return proto.CompactTextString(m) }
func (*AdminResponse) ProtoMessage()    {}
func (*AdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{2}
}

func (m *AdminResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminResponse.Unmarshal(m, b)
}
func (m *AdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminResponse.Marshal(b, m, deterministic)
}
func (m *AdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminResponse.Merge(m, src)
}
func (m *AdminResponse) XXX_Size() int {
	return xxx_messageInfo_AdminResponse.Size(m)
}
func (m *AdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminResponse proto.InternalMessageInfo

func (m *AdminResponse) GetAdmin() *Admin {
	if m != nil {
		return m.Admin
	}
	return nil
}

func (m *AdminResponse) GetAdmins() []*Admin {
	if m != nil {
		return m.Admins
	}
	return nil
}

func init() {
	proto.RegisterType((*Admin)(nil), "proto.Admin")
	proto.RegisterType((*AdminRequest)(nil), "proto.AdminRequest")
	proto.RegisterType((*AdminResponse)(nil), "proto.AdminResponse")
}

func init() { proto.RegisterFile("admin.proto", fileDescriptor_73a7fc70dcc2027c) }

var fileDescriptor_73a7fc70dcc2027c = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x31, 0x4f, 0xf3, 0x30,
	0x10, 0x86, 0xbf, 0xa4, 0x4d, 0x3f, 0x7a, 0x29, 0x0c, 0x86, 0xc1, 0xca, 0xd2, 0x28, 0xaa, 0x50,
	0x97, 0xa6, 0x52, 0x58, 0x50, 0x37, 0x60, 0x43, 0x48, 0x48, 0x29, 0x0c, 0xb0, 0xa5, 0xc9, 0x35,
	0x58, 0x34, 0x71, 0x88, 0x1d, 0x7e, 0x00, 0xbf, 0x1c, 0xf5, 0xec, 0x02, 0x15, 0x43, 0x99, 0x1c,
	0xdf, 0x3d, 0xef, 0xbd, 0x77, 0x17, 0x83, 0x9f, 0x15, 0x95, 0xa8, 0xe3, 0xa6, 0x95, 0x5a, 0x32,
	0x8f, 0x8e, 0x60, 0x94, 0xcb, 0xaa, 0x92, 0x36, 0x18, 0x8c, 0x4b, 0x29, 0xcb, 0x0d, 0xce, 0xe9,
	0xb6, 0xea, 0xd6, 0x73, 0x2d, 0x2a, 0x54, 0x3a, 0xab, 0x1a, 0x03, 0x44, 0x1f, 0x2e, 0x78, 0x57,
	0xdb, 0x2a, 0xec, 0x04, 0x5c, 0x51, 0x70, 0x27, 0x74, 0xa6, 0xc3, 0xd4, 0x15, 0x05, 0x1b, 0x43,
	0xbf, 0x53, 0xd8, 0x72, 0x37, 0x74, 0xa6, 0x7e, 0xe2, 0x1b, 0x3e, 0x7e, 0x54, 0xd8, 0xa6, 0x94,
	0x60, 0x97, 0x30, 0xdc, 0x64, 0x4a, 0xdf, 0xc9, 0x52, 0xd4, 0xbc, 0x47, 0x54, 0x10, 0x1b, 0xbf,
	0x78, 0xe7, 0x17, 0x3f, 0xec, 0xfc, 0xd2, 0x6f, 0x98, 0x2d, 0x00, 0x2a, 0x59, 0x88, 0xb5, 0xc0,
	0xe2, 0xbe, 0xe6, 0xfd, 0x83, 0xd2, 0x1f, 0xf4, 0xd6, 0x35, 0x6f, 0x31, 0xd3, 0x24, 0xf5, 0x0e,
	0xbb, 0x7e, 0xc1, 0x8c, 0xc3, 0x7f, 0xa1, 0x96, 0x5d, 0x83, 0x2d, 0x1f, 0x84, 0xce, 0xf4, 0x28,
	0xdd, 0x5d, 0xa3, 0x04, 0x46, 0xb4, 0x83, 0x14, 0xdf, 0x3a, 0x54, 0x9a, 0x45, 0xe0, 0xd1, 0x66,
	0x69, 0x1b, 0x7e, 0x32, 0xb2, 0xb3, 0x1b, 0xc6, 0xa4, 0xa2, 0x27, 0x38, 0xb6, 0x1a, 0xd5, 0xc8,
	0x5a, 0xe1, 0x5f, 0x44, 0x6c, 0x02, 0x03, 0xfa, 0x50, 0xdc, 0x0d, 0x7b, 0xbf, 0x20, 0x9b, 0x4b,
	0x6e, 0x6d, 0x3b, 0x4b, 0x6c, 0xdf, 0x45, 0x8e, 0x6c, 0x01, 0xfe, 0x0d, 0x4d, 0x61, 0x7e, 0xd4,
	0xe9, 0x9e, 0xc8, 0xb4, 0x1c, 0x9c, 0xed, 0x07, 0x4d, 0x4f, 0xd1, 0xbf, 0xeb, 0xf3, 0xe7, 0xc9,
	0x46, 0x94, 0x2f, 0x7a, 0xd6, 0x35, 0xb3, 0x55, 0x96, 0xbf, 0x62, 0x5d, 0xcc, 0xc9, 0x66, 0xa6,
	0x4c, 0x75, 0xfb, 0x34, 0x06, 0x74, 0x5c, 0x7c, 0x06, 0x00, 0x00, 0xff, 0xff, 0xa7, 0xf7, 0x62,
	0xf8, 0x53, 0x02, 0x00, 0x00,
}
