// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: admin.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	proto1 "light-up-backend/common/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AdminService service

type AdminService interface {
	// Education Qualification
	AddEducationQualification(ctx context.Context, in *CreateEducationQualificationRequest, opts ...client.CallOption) (*EducationQualificationResponse, error)
	GetEducationQualificationById(ctx context.Context, in *proto1.IdRequest, opts ...client.CallOption) (*EducationQualificationResponse, error)
	GetAllEducationQualifications(ctx context.Context, in *proto1.Empty, opts ...client.CallOption) (*EducationQualificationResponse, error)
}

type adminService struct {
	c    client.Client
	name string
}

func NewAdminService(name string, c client.Client) AdminService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "proto"
	}
	return &adminService{
		c:    c,
		name: name,
	}
}

func (c *adminService) AddEducationQualification(ctx context.Context, in *CreateEducationQualificationRequest, opts ...client.CallOption) (*EducationQualificationResponse, error) {
	req := c.c.NewRequest(c.name, "AdminService.AddEducationQualification", in)
	out := new(EducationQualificationResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminService) GetEducationQualificationById(ctx context.Context, in *proto1.IdRequest, opts ...client.CallOption) (*EducationQualificationResponse, error) {
	req := c.c.NewRequest(c.name, "AdminService.GetEducationQualificationById", in)
	out := new(EducationQualificationResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminService) GetAllEducationQualifications(ctx context.Context, in *proto1.Empty, opts ...client.CallOption) (*EducationQualificationResponse, error) {
	req := c.c.NewRequest(c.name, "AdminService.GetAllEducationQualifications", in)
	out := new(EducationQualificationResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AdminService service

type AdminServiceHandler interface {
	// Education Qualification
	AddEducationQualification(context.Context, *CreateEducationQualificationRequest, *EducationQualificationResponse) error
	GetEducationQualificationById(context.Context, *proto1.IdRequest, *EducationQualificationResponse) error
	GetAllEducationQualifications(context.Context, *proto1.Empty, *EducationQualificationResponse) error
}

func RegisterAdminServiceHandler(s server.Server, hdlr AdminServiceHandler, opts ...server.HandlerOption) error {
	type adminService interface {
		AddEducationQualification(ctx context.Context, in *CreateEducationQualificationRequest, out *EducationQualificationResponse) error
		GetEducationQualificationById(ctx context.Context, in *proto1.IdRequest, out *EducationQualificationResponse) error
		GetAllEducationQualifications(ctx context.Context, in *proto1.Empty, out *EducationQualificationResponse) error
	}
	type AdminService struct {
		adminService
	}
	h := &adminServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&AdminService{h}, opts...))
}

type adminServiceHandler struct {
	AdminServiceHandler
}

func (h *adminServiceHandler) AddEducationQualification(ctx context.Context, in *CreateEducationQualificationRequest, out *EducationQualificationResponse) error {
	return h.AdminServiceHandler.AddEducationQualification(ctx, in, out)
}

func (h *adminServiceHandler) GetEducationQualificationById(ctx context.Context, in *proto1.IdRequest, out *EducationQualificationResponse) error {
	return h.AdminServiceHandler.GetEducationQualificationById(ctx, in, out)
}

func (h *adminServiceHandler) GetAllEducationQualifications(ctx context.Context, in *proto1.Empty, out *EducationQualificationResponse) error {
	return h.AdminServiceHandler.GetAllEducationQualifications(ctx, in, out)
}
