// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	proto1 "light-up-backend/common/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Admin struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 *proto1.User         `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	LastLogin            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=lastLogin,proto3" json:"lastLogin,omitempty"`
	ModifiedOn           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=modifiedOn,proto3" json:"modifiedOn,omitempty"`
	CreatedOn            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	IsSuper              bool                 `protobuf:"varint,6,opt,name=isSuper,proto3" json:"isSuper,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Admin) Reset()         { *m = Admin{} }
func (m *Admin) String() string { return proto.CompactTextString(m) }
func (*Admin) ProtoMessage()    {}
func (*Admin) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{0}
}

func (m *Admin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Admin.Unmarshal(m, b)
}
func (m *Admin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Admin.Marshal(b, m, deterministic)
}
func (m *Admin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Admin.Merge(m, src)
}
func (m *Admin) XXX_Size() int {
	return xxx_messageInfo_Admin.Size(m)
}
func (m *Admin) XXX_DiscardUnknown() {
	xxx_messageInfo_Admin.DiscardUnknown(m)
}

var xxx_messageInfo_Admin proto.InternalMessageInfo

func (m *Admin) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Admin) GetUser() *proto1.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Admin) GetLastLogin() *timestamp.Timestamp {
	if m != nil {
		return m.LastLogin
	}
	return nil
}

func (m *Admin) GetModifiedOn() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedOn
	}
	return nil
}

func (m *Admin) GetCreatedOn() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedOn
	}
	return nil
}

func (m *Admin) GetIsSuper() bool {
	if m != nil {
		return m.IsSuper
	}
	return false
}

type CreateEducationQualificationRequest struct {
	EducationQualification *proto1.EducationQualification `protobuf:"bytes,1,opt,name=educationQualification,proto3" json:"educationQualification,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                       `json:"-"`
	XXX_unrecognized       []byte                         `json:"-"`
	XXX_sizecache          int32                          `json:"-"`
}

func (m *CreateEducationQualificationRequest) Reset()         { *m = CreateEducationQualificationRequest{} }
func (m *CreateEducationQualificationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEducationQualificationRequest) ProtoMessage()    {}
func (*CreateEducationQualificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{1}
}

func (m *CreateEducationQualificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEducationQualificationRequest.Unmarshal(m, b)
}
func (m *CreateEducationQualificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEducationQualificationRequest.Marshal(b, m, deterministic)
}
func (m *CreateEducationQualificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEducationQualificationRequest.Merge(m, src)
}
func (m *CreateEducationQualificationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEducationQualificationRequest.Size(m)
}
func (m *CreateEducationQualificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEducationQualificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEducationQualificationRequest proto.InternalMessageInfo

func (m *CreateEducationQualificationRequest) GetEducationQualification() *proto1.EducationQualification {
	if m != nil {
		return m.EducationQualification
	}
	return nil
}

type EducationQualificationResponse struct {
	EducationQualification  *proto1.EducationQualification   `protobuf:"bytes,1,opt,name=educationQualification,proto3" json:"educationQualification,omitempty"`
	EducationQualifications []*proto1.EducationQualification `protobuf:"bytes,2,rep,name=educationQualifications,proto3" json:"educationQualifications,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                         `json:"-"`
	XXX_unrecognized        []byte                           `json:"-"`
	XXX_sizecache           int32                            `json:"-"`
}

func (m *EducationQualificationResponse) Reset()         { *m = EducationQualificationResponse{} }
func (m *EducationQualificationResponse) String() string { return proto.CompactTextString(m) }
func (*EducationQualificationResponse) ProtoMessage()    {}
func (*EducationQualificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{2}
}

func (m *EducationQualificationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EducationQualificationResponse.Unmarshal(m, b)
}
func (m *EducationQualificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EducationQualificationResponse.Marshal(b, m, deterministic)
}
func (m *EducationQualificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EducationQualificationResponse.Merge(m, src)
}
func (m *EducationQualificationResponse) XXX_Size() int {
	return xxx_messageInfo_EducationQualificationResponse.Size(m)
}
func (m *EducationQualificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EducationQualificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EducationQualificationResponse proto.InternalMessageInfo

func (m *EducationQualificationResponse) GetEducationQualification() *proto1.EducationQualification {
	if m != nil {
		return m.EducationQualification
	}
	return nil
}

func (m *EducationQualificationResponse) GetEducationQualifications() []*proto1.EducationQualification {
	if m != nil {
		return m.EducationQualifications
	}
	return nil
}

func init() {
	proto.RegisterType((*Admin)(nil), "proto.Admin")
	proto.RegisterType((*CreateEducationQualificationRequest)(nil), "proto.CreateEducationQualificationRequest")
	proto.RegisterType((*EducationQualificationResponse)(nil), "proto.EducationQualificationResponse")
}

func init() { proto.RegisterFile("admin.proto", fileDescriptor_73a7fc70dcc2027c) }

var fileDescriptor_73a7fc70dcc2027c = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xcf, 0x4b, 0xe3, 0x40,
	0x14, 0xc7, 0x37, 0xe9, 0x8f, 0xdd, 0x4e, 0xca, 0xb2, 0xcc, 0x61, 0x37, 0x1b, 0xe8, 0x36, 0x64,
	0x55, 0x8a, 0xd0, 0x14, 0xea, 0x45, 0xbc, 0xb5, 0x22, 0x52, 0x10, 0xc4, 0xd4, 0x2a, 0xf4, 0x96,
	0x66, 0x5e, 0xe3, 0x60, 0x92, 0x89, 0x99, 0x89, 0x50, 0xf0, 0xe4, 0xdf, 0xe4, 0x1f, 0xe2, 0x9f,
	0x24, 0x9d, 0x24, 0xea, 0x21, 0xb1, 0xf5, 0xe0, 0x69, 0x78, 0x99, 0xcf, 0xfb, 0x7c, 0xc3, 0x4b,
	0x1e, 0xd2, 0x5c, 0x12, 0xd2, 0xc8, 0x8e, 0x13, 0x26, 0x18, 0x6e, 0xc8, 0xc3, 0x68, 0x7b, 0x2c,
	0x0c, 0x59, 0xfe, 0xd0, 0xe8, 0xfa, 0x8c, 0xf9, 0x01, 0x0c, 0x64, 0xb5, 0x48, 0x97, 0x03, 0x41,
	0x43, 0xe0, 0xc2, 0x0d, 0xe3, 0x0c, 0xb0, 0x1e, 0x55, 0xd4, 0x18, 0xad, 0x2d, 0xf8, 0x27, 0x52,
	0x29, 0xd1, 0x15, 0x53, 0xe9, 0xb5, 0x1c, 0x95, 0x12, 0xdc, 0x45, 0xf5, 0x94, 0x43, 0xa2, 0xab,
	0xa6, 0xd2, 0xd3, 0x86, 0x5a, 0xc6, 0xdb, 0x33, 0x0e, 0x89, 0x23, 0x2f, 0xf0, 0x21, 0x6a, 0x05,
	0x2e, 0x17, 0x67, 0xcc, 0xa7, 0x91, 0x5e, 0x93, 0x94, 0x61, 0x67, 0x79, 0x76, 0x91, 0x67, 0x5f,
	0x16, 0x79, 0xce, 0x1b, 0x8c, 0x8f, 0x10, 0x0a, 0x19, 0xa1, 0x4b, 0x0a, 0xe4, 0x3c, 0xd2, 0xeb,
	0x1b, 0x5b, 0xdf, 0xd1, 0xeb, 0x54, 0x2f, 0x01, 0x57, 0xc8, 0xd6, 0xc6, 0xe6, 0xd4, 0x57, 0x18,
	0xeb, 0xe8, 0x3b, 0xe5, 0xd3, 0x34, 0x86, 0x44, 0x6f, 0x9a, 0x4a, 0xef, 0x87, 0x53, 0x94, 0xd6,
	0x03, 0xfa, 0x7f, 0x2c, 0xb1, 0x13, 0x92, 0x7a, 0xae, 0xa0, 0x2c, 0xba, 0x48, 0xdd, 0x80, 0x2e,
	0x69, 0x56, 0x38, 0x70, 0x97, 0x02, 0x17, 0x78, 0x86, 0x7e, 0x43, 0x29, 0x20, 0xa7, 0xa6, 0x0d,
	0x3b, 0xf9, 0x8c, 0x2a, 0x2c, 0x15, 0xcd, 0xd6, 0xb3, 0x82, 0xfe, 0x55, 0x05, 0xf3, 0x98, 0x45,
	0x1c, 0xbe, 0x28, 0x19, 0x5f, 0xa3, 0x3f, 0xe5, 0x37, 0x5c, 0x57, 0xcd, 0xda, 0x66, 0x6f, 0x55,
	0xf7, 0xf0, 0x49, 0x45, 0x6d, 0xf9, 0x57, 0x4d, 0x21, 0xb9, 0xa7, 0x1e, 0xe0, 0x18, 0xfd, 0x1d,
	0x11, 0x52, 0xae, 0xc1, 0xfb, 0x79, 0xca, 0x16, 0xdf, 0xc0, 0xd8, 0xfd, 0xf8, 0x8d, 0xf2, 0x81,
	0x59, 0xdf, 0xf0, 0x1c, 0x75, 0x4e, 0x41, 0x94, 0x63, 0xe3, 0xd5, 0x84, 0xe0, 0x5f, 0xb9, 0x69,
	0x42, 0x3e, 0xed, 0xbe, 0x92, 0xee, 0x51, 0x10, 0x94, 0x93, 0x1c, 0xb7, 0x0b, 0x53, 0x18, 0x8b,
	0xd5, 0xd6, 0xde, 0xf1, 0xde, 0x7c, 0x27, 0xa0, 0xfe, 0x8d, 0xe8, 0xa7, 0x71, 0x7f, 0xe1, 0x7a,
	0xb7, 0x10, 0x91, 0x81, 0x5c, 0xf1, 0x3e, 0xcf, 0xe6, 0x98, 0xef, 0x71, 0x53, 0x1e, 0x07, 0x2f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x99, 0xe8, 0x7e, 0x5d, 0x00, 0x04, 0x00, 0x00,
}
