// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lightSeeker.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "light-up-backend/common/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LightSeeker struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string           `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string           `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string           `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string           `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Mobile               string           `protobuf:"bytes,6,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Country              string           `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	State                string           `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty"`
	City                 string           `protobuf:"bytes,9,opt,name=city,proto3" json:"city,omitempty"`
	Image                string           `protobuf:"bytes,10,opt,name=image,proto3" json:"image,omitempty"`
	IsActive             bool             `protobuf:"varint,11,opt,name=isActive,proto3" json:"isActive,omitempty"`
	Type                 proto1.UserTypes `protobuf:"varint,12,opt,name=type,proto3,enum=proto.UserTypes" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LightSeeker) Reset()         { *m = LightSeeker{} }
func (m *LightSeeker) String() string { return proto.CompactTextString(m) }
func (*LightSeeker) ProtoMessage()    {}
func (*LightSeeker) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f8be97e23d390a7, []int{0}
}

func (m *LightSeeker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LightSeeker.Unmarshal(m, b)
}
func (m *LightSeeker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LightSeeker.Marshal(b, m, deterministic)
}
func (m *LightSeeker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LightSeeker.Merge(m, src)
}
func (m *LightSeeker) XXX_Size() int {
	return xxx_messageInfo_LightSeeker.Size(m)
}
func (m *LightSeeker) XXX_DiscardUnknown() {
	xxx_messageInfo_LightSeeker.DiscardUnknown(m)
}

var xxx_messageInfo_LightSeeker proto.InternalMessageInfo

func (m *LightSeeker) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LightSeeker) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *LightSeeker) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *LightSeeker) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LightSeeker) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LightSeeker) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LightSeeker) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *LightSeeker) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *LightSeeker) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *LightSeeker) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *LightSeeker) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *LightSeeker) GetType() proto1.UserTypes {
	if m != nil {
		return m.Type
	}
	return proto1.UserTypes_LIGHTER
}

type CreateLightSeekerRequest struct {
	LightSeeker          *LightSeeker `protobuf:"bytes,1,opt,name=lightSeeker,proto3" json:"lightSeeker,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateLightSeekerRequest) Reset()         { *m = CreateLightSeekerRequest{} }
func (m *CreateLightSeekerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLightSeekerRequest) ProtoMessage()    {}
func (*CreateLightSeekerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f8be97e23d390a7, []int{1}
}

func (m *CreateLightSeekerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLightSeekerRequest.Unmarshal(m, b)
}
func (m *CreateLightSeekerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLightSeekerRequest.Marshal(b, m, deterministic)
}
func (m *CreateLightSeekerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLightSeekerRequest.Merge(m, src)
}
func (m *CreateLightSeekerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLightSeekerRequest.Size(m)
}
func (m *CreateLightSeekerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLightSeekerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLightSeekerRequest proto.InternalMessageInfo

func (m *CreateLightSeekerRequest) GetLightSeeker() *LightSeeker {
	if m != nil {
		return m.LightSeeker
	}
	return nil
}

type LightSeekerResponse struct {
	LightSeeker          *LightSeeker   `protobuf:"bytes,1,opt,name=lightSeeker,proto3" json:"lightSeeker,omitempty"`
	LightSeekers         []*LightSeeker `protobuf:"bytes,2,rep,name=lightSeekers,proto3" json:"lightSeekers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *LightSeekerResponse) Reset()         { *m = LightSeekerResponse{} }
func (m *LightSeekerResponse) String() string { return proto.CompactTextString(m) }
func (*LightSeekerResponse) ProtoMessage()    {}
func (*LightSeekerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f8be97e23d390a7, []int{2}
}

func (m *LightSeekerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LightSeekerResponse.Unmarshal(m, b)
}
func (m *LightSeekerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LightSeekerResponse.Marshal(b, m, deterministic)
}
func (m *LightSeekerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LightSeekerResponse.Merge(m, src)
}
func (m *LightSeekerResponse) XXX_Size() int {
	return xxx_messageInfo_LightSeekerResponse.Size(m)
}
func (m *LightSeekerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LightSeekerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LightSeekerResponse proto.InternalMessageInfo

func (m *LightSeekerResponse) GetLightSeeker() *LightSeeker {
	if m != nil {
		return m.LightSeeker
	}
	return nil
}

func (m *LightSeekerResponse) GetLightSeekers() []*LightSeeker {
	if m != nil {
		return m.LightSeekers
	}
	return nil
}

func init() {
	proto.RegisterType((*LightSeeker)(nil), "proto.LightSeeker")
	proto.RegisterType((*CreateLightSeekerRequest)(nil), "proto.CreateLightSeekerRequest")
	proto.RegisterType((*LightSeekerResponse)(nil), "proto.LightSeekerResponse")
}

func init() { proto.RegisterFile("lightSeeker.proto", fileDescriptor_9f8be97e23d390a7) }

var fileDescriptor_9f8be97e23d390a7 = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x6e, 0x92, 0x26, 0x93, 0xa8, 0xd0, 0x29, 0xa0, 0x55, 0x84, 0x44, 0x64, 0x71, 0x88,
	0x84, 0xdc, 0x4a, 0x01, 0x71, 0xe3, 0x40, 0x01, 0xa1, 0x22, 0x84, 0x90, 0x0b, 0x17, 0x6e, 0x1b,
	0x7b, 0x28, 0xab, 0xda, 0x5e, 0xb3, 0xbb, 0x29, 0xf2, 0x99, 0x5f, 0xc5, 0x81, 0xff, 0x86, 0x3c,
	0xeb, 0xa4, 0x0e, 0x50, 0x54, 0xf5, 0xb4, 0x7e, 0xf3, 0x3e, 0xc6, 0xfb, 0x6c, 0xd8, 0xcf, 0xd5,
	0xd9, 0x57, 0x77, 0x4a, 0x74, 0x4e, 0xe6, 0xb0, 0x32, 0xda, 0x69, 0xec, 0xf3, 0x31, 0x9d, 0xa4,
	0xba, 0x28, 0x74, 0xe9, 0x87, 0xd1, 0xaf, 0x10, 0xc6, 0xef, 0x2e, 0xa5, 0xb8, 0x07, 0xa1, 0xca,
	0x44, 0x30, 0x0b, 0xe6, 0xa3, 0x24, 0x54, 0x19, 0x3e, 0x80, 0xd1, 0x17, 0x65, 0xac, 0x7b, 0x2f,
	0x0b, 0x12, 0x21, 0x8f, 0x2f, 0x07, 0x38, 0x85, 0x61, 0x2e, 0x5b, 0x72, 0x87, 0xc9, 0x0d, 0xc6,
	0xbb, 0xd0, 0xa7, 0x42, 0xaa, 0x5c, 0xf4, 0x98, 0xf0, 0xa0, 0x71, 0x54, 0xd2, 0xda, 0xef, 0xda,
	0x64, 0xa2, 0xef, 0x1d, 0x6b, 0x8c, 0xf7, 0x61, 0x50, 0xe8, 0xa5, 0xca, 0x49, 0x0c, 0x98, 0x69,
	0x11, 0x0a, 0xd8, 0x4d, 0xf5, 0xaa, 0x74, 0xa6, 0x16, 0xbb, 0x4c, 0xac, 0x61, 0xb3, 0xc3, 0x3a,
	0xe9, 0x48, 0x0c, 0xfd, 0x0e, 0x06, 0x88, 0xd0, 0x4b, 0x95, 0xab, 0xc5, 0x88, 0x87, 0xfc, 0xdc,
	0x28, 0x55, 0x21, 0xcf, 0x48, 0x80, 0x57, 0x32, 0x68, 0xde, 0x46, 0xd9, 0x17, 0xa9, 0x53, 0x17,
	0x24, 0xc6, 0xb3, 0x60, 0x3e, 0x4c, 0x36, 0x18, 0x1f, 0x41, 0xcf, 0xd5, 0x15, 0x89, 0xc9, 0x2c,
	0x98, 0xef, 0x2d, 0xee, 0xf8, 0xbe, 0x0e, 0x3f, 0x59, 0x32, 0x1f, 0xeb, 0x8a, 0x6c, 0xc2, 0x6c,
	0xf4, 0x01, 0xc4, 0x4b, 0x43, 0xd2, 0x51, 0xa7, 0xc4, 0x84, 0xbe, 0xad, 0xc8, 0x3a, 0x7c, 0x0a,
	0xe3, 0xce, 0x57, 0xe0, 0x52, 0xc7, 0x0b, 0x6c, 0x83, 0xba, 0xfa, 0xae, 0x2c, 0xfa, 0x11, 0xc0,
	0xc1, 0x56, 0x98, 0xad, 0x74, 0x69, 0xe9, 0x66, 0x69, 0xf8, 0x0c, 0x26, 0x1d, 0x68, 0x45, 0x38,
	0xdb, 0xb9, 0xc2, 0xb6, 0xa5, 0x5b, 0xfc, 0x0c, 0x01, 0x3b, 0xec, 0x29, 0x99, 0x0b, 0x95, 0x12,
	0x26, 0xb0, 0xff, 0xd7, 0x75, 0xf1, 0x61, 0x9b, 0x76, 0x55, 0x11, 0xd3, 0xe9, 0x3f, 0xd6, 0xb5,
	0xd7, 0x8a, 0x6e, 0xe1, 0x2b, 0xc0, 0x37, 0xe4, 0x3a, 0xdc, 0x71, 0x7d, 0x92, 0xe1, 0xba, 0xf0,
	0x93, 0xec, 0x7a, 0x29, 0x6f, 0xe1, 0xde, 0x9f, 0x29, 0xaf, 0xf9, 0x8f, 0x3b, 0x68, 0x6d, 0x8c,
	0xae, 0x97, 0xf5, 0x1c, 0x6e, 0x6f, 0x67, 0x59, 0x9c, 0x6c, 0x52, 0x2a, 0x57, 0xff, 0xdf, 0x7e,
	0x1c, 0x7f, 0x7e, 0xcc, 0x5d, 0xc6, 0xab, 0x2a, 0x5e, 0xca, 0xf4, 0x9c, 0xca, 0xec, 0xc8, 0x0f,
	0x2c, 0x4b, 0x63, 0xeb, 0xdb, 0x3c, 0xe2, 0x90, 0xe5, 0x80, 0x8f, 0x27, 0xbf, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xec, 0x8a, 0x11, 0x43, 0xb3, 0x03, 0x00, 0x00,
}
