// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lightSeeker.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	proto1 "light-up-backend/common/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LightSeeker struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 *proto1.User         `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	LastLogin            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=lastLogin,proto3" json:"lastLogin,omitempty"`
	ModifiedOn           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=modifiedOn,proto3" json:"modifiedOn,omitempty"`
	CreatedOn            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LightSeeker) Reset()         { *m = LightSeeker{} }
func (m *LightSeeker) String() string { return proto.CompactTextString(m) }
func (*LightSeeker) ProtoMessage()    {}
func (*LightSeeker) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f8be97e23d390a7, []int{0}
}

func (m *LightSeeker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LightSeeker.Unmarshal(m, b)
}
func (m *LightSeeker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LightSeeker.Marshal(b, m, deterministic)
}
func (m *LightSeeker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LightSeeker.Merge(m, src)
}
func (m *LightSeeker) XXX_Size() int {
	return xxx_messageInfo_LightSeeker.Size(m)
}
func (m *LightSeeker) XXX_DiscardUnknown() {
	xxx_messageInfo_LightSeeker.DiscardUnknown(m)
}

var xxx_messageInfo_LightSeeker proto.InternalMessageInfo

func (m *LightSeeker) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LightSeeker) GetUser() *proto1.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LightSeeker) GetLastLogin() *timestamp.Timestamp {
	if m != nil {
		return m.LastLogin
	}
	return nil
}

func (m *LightSeeker) GetModifiedOn() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedOn
	}
	return nil
}

func (m *LightSeeker) GetCreatedOn() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedOn
	}
	return nil
}

type LightSeekerRequest struct {
	LightSeeker          *LightSeeker `protobuf:"bytes,1,opt,name=lightSeeker,proto3" json:"lightSeeker,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LightSeekerRequest) Reset()         { *m = LightSeekerRequest{} }
func (m *LightSeekerRequest) String() string { return proto.CompactTextString(m) }
func (*LightSeekerRequest) ProtoMessage()    {}
func (*LightSeekerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f8be97e23d390a7, []int{1}
}

func (m *LightSeekerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LightSeekerRequest.Unmarshal(m, b)
}
func (m *LightSeekerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LightSeekerRequest.Marshal(b, m, deterministic)
}
func (m *LightSeekerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LightSeekerRequest.Merge(m, src)
}
func (m *LightSeekerRequest) XXX_Size() int {
	return xxx_messageInfo_LightSeekerRequest.Size(m)
}
func (m *LightSeekerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LightSeekerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LightSeekerRequest proto.InternalMessageInfo

func (m *LightSeekerRequest) GetLightSeeker() *LightSeeker {
	if m != nil {
		return m.LightSeeker
	}
	return nil
}

type LightSeekerResponse struct {
	LightSeeker          *LightSeeker   `protobuf:"bytes,1,opt,name=lightSeeker,proto3" json:"lightSeeker,omitempty"`
	LightSeekers         []*LightSeeker `protobuf:"bytes,2,rep,name=lightSeekers,proto3" json:"lightSeekers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *LightSeekerResponse) Reset()         { *m = LightSeekerResponse{} }
func (m *LightSeekerResponse) String() string { return proto.CompactTextString(m) }
func (*LightSeekerResponse) ProtoMessage()    {}
func (*LightSeekerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f8be97e23d390a7, []int{2}
}

func (m *LightSeekerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LightSeekerResponse.Unmarshal(m, b)
}
func (m *LightSeekerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LightSeekerResponse.Marshal(b, m, deterministic)
}
func (m *LightSeekerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LightSeekerResponse.Merge(m, src)
}
func (m *LightSeekerResponse) XXX_Size() int {
	return xxx_messageInfo_LightSeekerResponse.Size(m)
}
func (m *LightSeekerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LightSeekerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LightSeekerResponse proto.InternalMessageInfo

func (m *LightSeekerResponse) GetLightSeeker() *LightSeeker {
	if m != nil {
		return m.LightSeeker
	}
	return nil
}

func (m *LightSeekerResponse) GetLightSeekers() []*LightSeeker {
	if m != nil {
		return m.LightSeekers
	}
	return nil
}

func init() {
	proto.RegisterType((*LightSeeker)(nil), "proto.LightSeeker")
	proto.RegisterType((*LightSeekerRequest)(nil), "proto.LightSeekerRequest")
	proto.RegisterType((*LightSeekerResponse)(nil), "proto.LightSeekerResponse")
}

func init() { proto.RegisterFile("lightSeeker.proto", fileDescriptor_9f8be97e23d390a7) }

var fileDescriptor_9f8be97e23d390a7 = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xc1, 0xaa, 0xd3, 0x40,
	0x14, 0x86, 0x4d, 0x7a, 0xaf, 0x70, 0x4f, 0x8a, 0x7a, 0xe7, 0x22, 0xe6, 0x66, 0xd3, 0x92, 0x55,
	0x41, 0x92, 0x42, 0x15, 0x11, 0xc1, 0x4d, 0x55, 0x24, 0xb5, 0x20, 0xa4, 0xea, 0xc2, 0x5d, 0x9a,
	0x39, 0x8d, 0x43, 0x93, 0x4c, 0xcc, 0x4c, 0x84, 0xae, 0x7d, 0x3c, 0xdf, 0xc5, 0x67, 0x90, 0xce,
	0xa4, 0xed, 0x44, 0x2a, 0xad, 0xe2, 0x6a, 0x98, 0x39, 0xff, 0xff, 0x1d, 0xfe, 0x73, 0x12, 0xb8,
	0xce, 0x59, 0xf6, 0x45, 0x2e, 0x10, 0xd7, 0x58, 0x87, 0x55, 0xcd, 0x25, 0x27, 0x97, 0xea, 0xf0,
	0xfa, 0x29, 0x2f, 0x0a, 0x5e, 0xea, 0x47, 0x6f, 0x90, 0x71, 0x9e, 0xe5, 0x38, 0x56, 0xb7, 0x65,
	0xb3, 0x1a, 0x4b, 0x56, 0xa0, 0x90, 0x49, 0x51, 0x69, 0x81, 0xff, 0xd3, 0x02, 0x67, 0x7e, 0x60,
	0x91, 0x7b, 0x60, 0x33, 0xea, 0x5a, 0x43, 0x6b, 0x74, 0x15, 0xdb, 0x8c, 0x92, 0x01, 0x5c, 0x34,
	0x02, 0x6b, 0xd7, 0x1e, 0x5a, 0x23, 0x67, 0xe2, 0x68, 0x57, 0xf8, 0x51, 0x60, 0x1d, 0xab, 0x02,
	0x79, 0x0e, 0x57, 0x79, 0x22, 0xe4, 0x9c, 0x67, 0xac, 0x74, 0x7b, 0x4a, 0xe5, 0x85, 0xba, 0x6b,
	0xb8, 0xeb, 0x1a, 0x7e, 0xd8, 0x75, 0x8d, 0x0f, 0x62, 0xf2, 0x02, 0xa0, 0xe0, 0x94, 0xad, 0x18,
	0xd2, 0xf7, 0xa5, 0x7b, 0x71, 0xd2, 0x6a, 0xa8, 0xb7, 0x5d, 0xd3, 0x1a, 0x13, 0xa9, 0xac, 0x97,
	0xa7, 0xbb, 0xee, 0xc5, 0xfe, 0x0c, 0x88, 0x91, 0x37, 0xc6, 0xaf, 0x0d, 0x0a, 0x49, 0x9e, 0x82,
	0x63, 0x4c, 0x54, 0xe5, 0x77, 0x26, 0xa4, 0x4d, 0x6b, 0xea, 0x4d, 0x99, 0xff, 0xdd, 0x82, 0x9b,
	0x0e, 0x4c, 0x54, 0xbc, 0x14, 0xf8, 0x6f, 0x34, 0xf2, 0x0c, 0xfa, 0xc6, 0x55, 0xb8, 0xf6, 0xb0,
	0xf7, 0x07, 0x5b, 0x47, 0x37, 0xf9, 0xd1, 0xeb, 0x44, 0x5a, 0x60, 0xfd, 0x8d, 0xa5, 0x48, 0xe6,
	0x70, 0xfd, 0x4a, 0xa5, 0x36, 0xd7, 0x7b, 0x7b, 0x84, 0xa6, 0x47, 0xe0, 0x79, 0xc7, 0x4a, 0x3a,
	0x90, 0x7f, 0x87, 0xbc, 0x06, 0xf2, 0x16, 0xa5, 0x51, 0x9b, 0x6e, 0x22, 0x4a, 0x1e, 0xb4, 0x9e,
	0x88, 0x9e, 0x47, 0x99, 0xc1, 0xc3, 0xdf, 0x29, 0x6f, 0x8a, 0x84, 0xe5, 0xe4, 0xa6, 0xb5, 0xa9,
	0xdb, 0x79, 0xac, 0x97, 0x70, 0xbf, 0xcb, 0x12, 0xa4, 0xbf, 0xa7, 0x54, 0x72, 0x73, 0xc2, 0x1e,
	0xc1, 0xa3, 0x4f, 0x49, 0xce, 0x68, 0x77, 0x40, 0xdb, 0x0f, 0xfb, 0xaf, 0x53, 0xbd, 0x83, 0xdb,
	0xa8, 0xfc, 0x4f, 0xb0, 0x69, 0xf0, 0xf9, 0xb1, 0xda, 0x6e, 0xd0, 0x54, 0xc1, 0x32, 0x49, 0xd7,
	0x58, 0xd2, 0xb1, 0x7e, 0x10, 0x4a, 0x1a, 0x08, 0xbd, 0xdf, 0xf6, 0x97, 0xbe, 0xab, 0x8e, 0x27,
	0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xf2, 0x6c, 0x7f, 0x11, 0x04, 0x00, 0x00,
}
