// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserTypes int32

const (
	UserTypes_LIGHTER      UserTypes = 0
	UserTypes_LIGHT_SEEKER UserTypes = 1
	UserTypes_ADMIN        UserTypes = 2
)

var UserTypes_name = map[int32]string{
	0: "LIGHTER",
	1: "LIGHT_SEEKER",
	2: "ADMIN",
}

var UserTypes_value = map[string]int32{
	"LIGHTER":      0,
	"LIGHT_SEEKER": 1,
	"ADMIN":        2,
}

func (x UserTypes) String() string {
	return proto.EnumName(UserTypes_name, int32(x))
}

func (UserTypes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type Occupations int32

const (
	Occupations_UNKNOWN       Occupations = 0
	Occupations_STUDENT       Occupations = 1
	Occupations_BUSINESS      Occupations = 2
	Occupations_SALARIED_JOB  Occupations = 3
	Occupations_SELF_EMPLOYED Occupations = 4
	Occupations_UN_EMPLOYED   Occupations = 5
	Occupations_OTHER         Occupations = 6
)

var Occupations_name = map[int32]string{
	0: "UNKNOWN",
	1: "STUDENT",
	2: "BUSINESS",
	3: "SALARIED_JOB",
	4: "SELF_EMPLOYED",
	5: "UN_EMPLOYED",
	6: "OTHER",
}

var Occupations_value = map[string]int32{
	"UNKNOWN":       0,
	"STUDENT":       1,
	"BUSINESS":      2,
	"SALARIED_JOB":  3,
	"SELF_EMPLOYED": 4,
	"UN_EMPLOYED":   5,
	"OTHER":         6,
}

func (x Occupations) String() string {
	return proto.EnumName(Occupations_name, int32(x))
}

func (Occupations) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

type IdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdRequest) Reset()         { *m = IdRequest{} }
func (m *IdRequest) String() string { return proto.CompactTextString(m) }
func (*IdRequest) ProtoMessage()    {}
func (*IdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *IdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdRequest.Unmarshal(m, b)
}
func (m *IdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdRequest.Marshal(b, m, deterministic)
}
func (m *IdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdRequest.Merge(m, src)
}
func (m *IdRequest) XXX_Size() int {
	return xxx_messageInfo_IdRequest.Size(m)
}
func (m *IdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdRequest proto.InternalMessageInfo

func (m *IdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type EmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailRequest) Reset()         { *m = EmailRequest{} }
func (m *EmailRequest) String() string { return proto.CompactTextString(m) }
func (*EmailRequest) ProtoMessage()    {}
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *EmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailRequest.Unmarshal(m, b)
}
func (m *EmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailRequest.Marshal(b, m, deterministic)
}
func (m *EmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailRequest.Merge(m, src)
}
func (m *EmailRequest) XXX_Size() int {
	return xxx_messageInfo_EmailRequest.Size(m)
}
func (m *EmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailRequest proto.InternalMessageInfo

func (m *EmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type IdsRequest struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdsRequest) Reset()         { *m = IdsRequest{} }
func (m *IdsRequest) String() string { return proto.CompactTextString(m) }
func (*IdsRequest) ProtoMessage()    {}
func (*IdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *IdsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdsRequest.Unmarshal(m, b)
}
func (m *IdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdsRequest.Marshal(b, m, deterministic)
}
func (m *IdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdsRequest.Merge(m, src)
}
func (m *IdsRequest) XXX_Size() int {
	return xxx_messageInfo_IdsRequest.Size(m)
}
func (m *IdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdsRequest proto.InternalMessageInfo

func (m *IdsRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type User struct {
	FirstName              string      `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName               string      `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                  string      `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password               string      `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Mobile                 string      `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Address                *Address    `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	ProfilePictureURL      string      `protobuf:"bytes,7,opt,name=profilePictureURL,proto3" json:"profilePictureURL,omitempty"`
	Type                   UserTypes   `protobuf:"varint,8,opt,name=type,proto3,enum=proto.UserTypes" json:"type,omitempty"`
	Occupation             Occupations `protobuf:"varint,9,opt,name=occupation,proto3,enum=proto.Occupations" json:"occupation,omitempty"`
	EducationQualification string      `protobuf:"bytes,10,opt,name=educationQualification,proto3" json:"educationQualification,omitempty"`
	IsValid                bool        `protobuf:"varint,11,opt,name=isValid,proto3" json:"isValid,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}    `json:"-"`
	XXX_unrecognized       []byte      `json:"-"`
	XXX_sizecache          int32       `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *User) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *User) GetProfilePictureURL() string {
	if m != nil {
		return m.ProfilePictureURL
	}
	return ""
}

func (m *User) GetType() UserTypes {
	if m != nil {
		return m.Type
	}
	return UserTypes_LIGHTER
}

func (m *User) GetOccupation() Occupations {
	if m != nil {
		return m.Occupation
	}
	return Occupations_UNKNOWN
}

func (m *User) GetEducationQualification() string {
	if m != nil {
		return m.EducationQualification
	}
	return ""
}

func (m *User) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

type Address struct {
	City                 string   `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Country              string   `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Zip                  string   `protobuf:"bytes,4,opt,name=zip,proto3" json:"zip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{5}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Address) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

type EducationQualification struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EducationQualification) Reset()         { *m = EducationQualification{} }
func (m *EducationQualification) String() string { return proto.CompactTextString(m) }
func (*EducationQualification) ProtoMessage()    {}
func (*EducationQualification) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{6}
}

func (m *EducationQualification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EducationQualification.Unmarshal(m, b)
}
func (m *EducationQualification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EducationQualification.Marshal(b, m, deterministic)
}
func (m *EducationQualification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EducationQualification.Merge(m, src)
}
func (m *EducationQualification) XXX_Size() int {
	return xxx_messageInfo_EducationQualification.Size(m)
}
func (m *EducationQualification) XXX_DiscardUnknown() {
	xxx_messageInfo_EducationQualification.DiscardUnknown(m)
}

var xxx_messageInfo_EducationQualification proto.InternalMessageInfo

func (m *EducationQualification) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EducationQualification) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.UserTypes", UserTypes_name, UserTypes_value)
	proto.RegisterEnum("proto.Occupations", Occupations_name, Occupations_value)
	proto.RegisterType((*IdRequest)(nil), "proto.IdRequest")
	proto.RegisterType((*EmailRequest)(nil), "proto.EmailRequest")
	proto.RegisterType((*IdsRequest)(nil), "proto.IdsRequest")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*Address)(nil), "proto.Address")
	proto.RegisterType((*EducationQualification)(nil), "proto.EducationQualification")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 544 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x5d, 0x6f, 0xd3, 0x3c,
	0x14, 0xc7, 0x97, 0xbe, 0xa5, 0x39, 0xed, 0xb3, 0xc7, 0xb3, 0xd0, 0x14, 0xf1, 0x5a, 0x45, 0xbb,
	0x88, 0x26, 0xb6, 0x49, 0x43, 0x70, 0xc5, 0x4d, 0xa7, 0x1a, 0x16, 0xd6, 0xa5, 0xc3, 0x69, 0x40,
	0x70, 0x53, 0x65, 0x89, 0x07, 0x16, 0x49, 0x13, 0x62, 0x07, 0x54, 0x3e, 0x04, 0x9f, 0x19, 0xd9,
	0x49, 0xd6, 0x89, 0x97, 0x2b, 0x9f, 0x9f, 0xff, 0xc7, 0xc7, 0xc7, 0xe7, 0x9f, 0xc0, 0x38, 0xce,
	0xb3, 0x2c, 0x5f, 0x1f, 0x17, 0x65, 0x2e, 0x73, 0xdc, 0xd7, 0x8b, 0xf3, 0x00, 0x2c, 0x2f, 0xa1,
	0xec, 0x6b, 0xc5, 0x84, 0xc4, 0xbb, 0xd0, 0xe1, 0x89, 0x6d, 0x4c, 0x0c, 0xd7, 0xa2, 0x1d, 0x9e,
	0x38, 0x07, 0x30, 0x26, 0x59, 0xc4, 0xd3, 0x56, 0xbf, 0x07, 0x7d, 0xa6, 0xb8, 0x49, 0xa9, 0xc1,
	0x79, 0x0c, 0xe0, 0x25, 0xa2, 0xcd, 0x41, 0xd0, 0xe5, 0x89, 0xb0, 0x8d, 0x49, 0xd7, 0xb5, 0xa8,
	0x0a, 0x1d, 0x13, 0xfa, 0x24, 0x2b, 0xe4, 0xc6, 0xf9, 0xd9, 0x85, 0x5e, 0x28, 0x58, 0x89, 0x1f,
	0x82, 0x75, 0xc3, 0x4b, 0x21, 0xfd, 0x28, 0x63, 0x4d, 0xad, 0xed, 0x06, 0xbe, 0x0f, 0xc3, 0x34,
	0x6a, 0xc4, 0x8e, 0x16, 0x6f, 0x79, 0xdb, 0x41, 0xf7, 0x4e, 0x07, 0xea, 0x44, 0x11, 0x09, 0xf1,
	0x3d, 0x2f, 0x13, 0xbb, 0x57, 0x9f, 0x68, 0x19, 0xef, 0xc3, 0x20, 0xcb, 0xaf, 0x79, 0xca, 0xec,
	0xbe, 0x56, 0x1a, 0xc2, 0x2e, 0x98, 0x51, 0x92, 0x94, 0x4c, 0x08, 0x7b, 0x30, 0x31, 0xdc, 0xd1,
	0xe9, 0x6e, 0x3d, 0x98, 0xe3, 0x69, 0xbd, 0x4b, 0x5b, 0x19, 0x3f, 0x85, 0xbd, 0xa2, 0xcc, 0x6f,
	0x78, 0xca, 0xae, 0x78, 0x2c, 0xab, 0x92, 0x85, 0x74, 0x6e, 0x9b, 0xba, 0xd8, 0x9f, 0x02, 0x3e,
	0x80, 0x9e, 0xdc, 0x14, 0xcc, 0x1e, 0x4e, 0x0c, 0x77, 0xf7, 0x14, 0x35, 0x45, 0xd5, 0xb3, 0x97,
	0x9b, 0x82, 0x09, 0xaa, 0x55, 0x7c, 0x0a, 0x90, 0xc7, 0x71, 0x55, 0x44, 0x92, 0xe7, 0x6b, 0xdb,
	0xd2, 0xb9, 0xb8, 0xc9, 0x5d, 0xdc, 0x0a, 0x82, 0xde, 0xc9, 0xc2, 0x2f, 0x60, 0x9f, 0x25, 0x55,
	0xac, 0xe1, 0x6d, 0x15, 0xa5, 0xfc, 0x86, 0xd7, 0x60, 0x83, 0x6e, 0xe6, 0x1f, 0x2a, 0xb6, 0xc1,
	0xe4, 0xe2, 0x5d, 0x94, 0xf2, 0xc4, 0x1e, 0x4d, 0x0c, 0x77, 0x48, 0x5b, 0x74, 0x56, 0x60, 0x36,
	0xaf, 0xc5, 0x18, 0x7a, 0x31, 0x97, 0x9b, 0xc6, 0x0d, 0x1d, 0xab, 0x61, 0x0b, 0x19, 0xc9, 0xd6,
	0x85, 0x1a, 0x54, 0xb9, 0x38, 0xaf, 0xd6, 0xb2, 0xdc, 0x34, 0x26, 0xb4, 0xa8, 0xac, 0xff, 0xc1,
	0x8b, 0xc6, 0x01, 0x15, 0x3a, 0x2f, 0x61, 0x9f, 0xfc, 0xbd, 0xa9, 0xdf, 0x3e, 0x35, 0x75, 0xff,
	0x7a, 0x6b, 0xb8, 0x8e, 0x0f, 0x9f, 0x83, 0x75, 0x3b, 0x37, 0x3c, 0x02, 0x73, 0xee, 0xbd, 0x3e,
	0x5f, 0x12, 0x8a, 0x76, 0x30, 0x82, 0xb1, 0x86, 0x55, 0x40, 0xc8, 0x05, 0xa1, 0xc8, 0xc0, 0x16,
	0xf4, 0xa7, 0xb3, 0x4b, 0xcf, 0x47, 0x9d, 0xc3, 0x6f, 0x30, 0xba, 0x33, 0x42, 0x75, 0x30, 0xf4,
	0x2f, 0xfc, 0xc5, 0x7b, 0x1f, 0xed, 0x28, 0x08, 0x96, 0xe1, 0x8c, 0xf8, 0x4b, 0x64, 0xe0, 0x31,
	0x0c, 0xcf, 0xc2, 0xc0, 0xf3, 0x49, 0x10, 0xa0, 0x8e, 0xaa, 0x19, 0x4c, 0xe7, 0x53, 0xea, 0x91,
	0xd9, 0xea, 0xcd, 0xe2, 0x0c, 0x75, 0xf1, 0x1e, 0xfc, 0x17, 0x90, 0xf9, 0xab, 0x15, 0xb9, 0xbc,
	0x9a, 0x2f, 0x3e, 0x90, 0x19, 0xea, 0xe1, 0xff, 0x61, 0x14, 0xfa, 0xdb, 0x8d, 0xbe, 0xba, 0x77,
	0xb1, 0x3c, 0x27, 0x14, 0x0d, 0xce, 0x9e, 0x7c, 0x7c, 0x94, 0xf2, 0x4f, 0x9f, 0xe5, 0x51, 0x55,
	0x1c, 0x5d, 0x47, 0xf1, 0x17, 0xb6, 0x4e, 0x4e, 0xea, 0x5f, 0xee, 0x44, 0x1b, 0x7b, 0x3d, 0xd0,
	0xcb, 0xb3, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xea, 0xda, 0x4b, 0x25, 0x89, 0x03, 0x00, 0x00,
}
