// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserTypes int32

const (
	UserTypes_LIGHTER      UserTypes = 0
	UserTypes_LIGHT_SEEKER UserTypes = 1
	UserTypes_ADMIN        UserTypes = 2
)

var UserTypes_name = map[int32]string{
	0: "LIGHTER",
	1: "LIGHT_SEEKER",
	2: "ADMIN",
}

var UserTypes_value = map[string]int32{
	"LIGHTER":      0,
	"LIGHT_SEEKER": 1,
	"ADMIN":        2,
}

func (x UserTypes) String() string {
	return proto.EnumName(UserTypes_name, int32(x))
}

func (UserTypes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type InstituteType int32

const (
	InstituteType_INSTITUTE_TYPE_UNKNOWN InstituteType = 0
	InstituteType_INDIVIDUAL             InstituteType = 1
	InstituteType_EDUCATIONAL_INSTITUTE  InstituteType = 2
	InstituteType_COUNSELLING_INSTITUTE  InstituteType = 3
	InstituteType_FOREIGN_STUDY          InstituteType = 4
	InstituteType_DMIT_CENTER            InstituteType = 5
)

var InstituteType_name = map[int32]string{
	0: "INSTITUTE_TYPE_UNKNOWN",
	1: "INDIVIDUAL",
	2: "EDUCATIONAL_INSTITUTE",
	3: "COUNSELLING_INSTITUTE",
	4: "FOREIGN_STUDY",
	5: "DMIT_CENTER",
}

var InstituteType_value = map[string]int32{
	"INSTITUTE_TYPE_UNKNOWN": 0,
	"INDIVIDUAL":             1,
	"EDUCATIONAL_INSTITUTE":  2,
	"COUNSELLING_INSTITUTE":  3,
	"FOREIGN_STUDY":          4,
	"DMIT_CENTER":            5,
}

func (x InstituteType) String() string {
	return proto.EnumName(InstituteType_name, int32(x))
}

func (InstituteType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

type OccupationType int32

const (
	OccupationType_UNKNOWN       OccupationType = 0
	OccupationType_STUDENT       OccupationType = 1
	OccupationType_BUSINESS      OccupationType = 2
	OccupationType_SALARIED_JOB  OccupationType = 3
	OccupationType_SELF_EMPLOYED OccupationType = 4
	OccupationType_UN_EMPLOYED   OccupationType = 5
	OccupationType_OTHER         OccupationType = 6
)

var OccupationType_name = map[int32]string{
	0: "UNKNOWN",
	1: "STUDENT",
	2: "BUSINESS",
	3: "SALARIED_JOB",
	4: "SELF_EMPLOYED",
	5: "UN_EMPLOYED",
	6: "OTHER",
}

var OccupationType_value = map[string]int32{
	"UNKNOWN":       0,
	"STUDENT":       1,
	"BUSINESS":      2,
	"SALARIED_JOB":  3,
	"SELF_EMPLOYED": 4,
	"UN_EMPLOYED":   5,
	"OTHER":         6,
}

func (x OccupationType) String() string {
	return proto.EnumName(OccupationType_name, int32(x))
}

func (OccupationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

type IdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdRequest) Reset()         { *m = IdRequest{} }
func (m *IdRequest) String() string { return proto.CompactTextString(m) }
func (*IdRequest) ProtoMessage()    {}
func (*IdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *IdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdRequest.Unmarshal(m, b)
}
func (m *IdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdRequest.Marshal(b, m, deterministic)
}
func (m *IdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdRequest.Merge(m, src)
}
func (m *IdRequest) XXX_Size() int {
	return xxx_messageInfo_IdRequest.Size(m)
}
func (m *IdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdRequest proto.InternalMessageInfo

func (m *IdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type EmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailRequest) Reset()         { *m = EmailRequest{} }
func (m *EmailRequest) String() string { return proto.CompactTextString(m) }
func (*EmailRequest) ProtoMessage()    {}
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *EmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailRequest.Unmarshal(m, b)
}
func (m *EmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailRequest.Marshal(b, m, deterministic)
}
func (m *EmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailRequest.Merge(m, src)
}
func (m *EmailRequest) XXX_Size() int {
	return xxx_messageInfo_EmailRequest.Size(m)
}
func (m *EmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailRequest proto.InternalMessageInfo

func (m *EmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type IdsRequest struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdsRequest) Reset()         { *m = IdsRequest{} }
func (m *IdsRequest) String() string { return proto.CompactTextString(m) }
func (*IdsRequest) ProtoMessage()    {}
func (*IdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *IdsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdsRequest.Unmarshal(m, b)
}
func (m *IdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdsRequest.Marshal(b, m, deterministic)
}
func (m *IdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdsRequest.Merge(m, src)
}
func (m *IdsRequest) XXX_Size() int {
	return xxx_messageInfo_IdsRequest.Size(m)
}
func (m *IdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdsRequest proto.InternalMessageInfo

func (m *IdsRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type User struct {
	FirstName              string      `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName               string      `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                  string      `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password               string      `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Mobile                 string      `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Address                *Location   `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	ProfilePictureURL      string      `protobuf:"bytes,7,opt,name=profilePictureURL,proto3" json:"profilePictureURL,omitempty"`
	Type                   UserTypes   `protobuf:"varint,8,opt,name=type,proto3,enum=proto.UserTypes" json:"type,omitempty"`
	Occupation             *Occupation `protobuf:"bytes,9,opt,name=occupation,proto3" json:"occupation,omitempty"`
	EducationQualification string      `protobuf:"bytes,10,opt,name=educationQualification,proto3" json:"educationQualification,omitempty"`
	IsValid                bool        `protobuf:"varint,11,opt,name=isValid,proto3" json:"isValid,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}    `json:"-"`
	XXX_unrecognized       []byte      `json:"-"`
	XXX_sizecache          int32       `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *User) GetAddress() *Location {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *User) GetProfilePictureURL() string {
	if m != nil {
		return m.ProfilePictureURL
	}
	return ""
}

func (m *User) GetType() UserTypes {
	if m != nil {
		return m.Type
	}
	return UserTypes_LIGHTER
}

func (m *User) GetOccupation() *Occupation {
	if m != nil {
		return m.Occupation
	}
	return nil
}

func (m *User) GetEducationQualification() string {
	if m != nil {
		return m.EducationQualification
	}
	return ""
}

func (m *User) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

type Address struct {
	AddressLine1         string    `protobuf:"bytes,1,opt,name=addressLine1,proto3" json:"addressLine1,omitempty"`
	AddressLine2         string    `protobuf:"bytes,2,opt,name=addressLine2,proto3" json:"addressLine2,omitempty"`
	Location             *Location `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{5}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAddressLine1() string {
	if m != nil {
		return m.AddressLine1
	}
	return ""
}

func (m *Address) GetAddressLine2() string {
	if m != nil {
		return m.AddressLine2
	}
	return ""
}

func (m *Address) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type Location struct {
	City                 string   `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Country              string   `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Zip                  string   `protobuf:"bytes,4,opt,name=zip,proto3" json:"zip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{6}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Location) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Location) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Location) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

type EducationQualification struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EducationQualification) Reset()         { *m = EducationQualification{} }
func (m *EducationQualification) String() string { return proto.CompactTextString(m) }
func (*EducationQualification) ProtoMessage()    {}
func (*EducationQualification) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{7}
}

func (m *EducationQualification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EducationQualification.Unmarshal(m, b)
}
func (m *EducationQualification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EducationQualification.Marshal(b, m, deterministic)
}
func (m *EducationQualification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EducationQualification.Merge(m, src)
}
func (m *EducationQualification) XXX_Size() int {
	return xxx_messageInfo_EducationQualification.Size(m)
}
func (m *EducationQualification) XXX_DiscardUnknown() {
	xxx_messageInfo_EducationQualification.DiscardUnknown(m)
}

var xxx_messageInfo_EducationQualification proto.InternalMessageInfo

func (m *EducationQualification) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EducationQualification) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Institute struct {
	Id                                string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                              InstituteType `protobuf:"varint,2,opt,name=type,proto3,enum=proto.InstituteType" json:"type,omitempty"`
	PriorCounsellingExperience        bool          `protobuf:"varint,3,opt,name=priorCounsellingExperience,proto3" json:"priorCounsellingExperience,omitempty"`
	PriorCounsellingExperienceInYears int32         `protobuf:"varint,4,opt,name=priorCounsellingExperienceInYears,proto3" json:"priorCounsellingExperienceInYears,omitempty"`
	IsCertified                       bool          `protobuf:"varint,5,opt,name=isCertified,proto3" json:"isCertified,omitempty"`
	CertificationType                 string        `protobuf:"bytes,6,opt,name=certificationType,proto3" json:"certificationType,omitempty"`
	Address                           *Address      `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral              struct{}      `json:"-"`
	XXX_unrecognized                  []byte        `json:"-"`
	XXX_sizecache                     int32         `json:"-"`
}

func (m *Institute) Reset()         { *m = Institute{} }
func (m *Institute) String() string { return proto.CompactTextString(m) }
func (*Institute) ProtoMessage()    {}
func (*Institute) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{8}
}

func (m *Institute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Institute.Unmarshal(m, b)
}
func (m *Institute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Institute.Marshal(b, m, deterministic)
}
func (m *Institute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Institute.Merge(m, src)
}
func (m *Institute) XXX_Size() int {
	return xxx_messageInfo_Institute.Size(m)
}
func (m *Institute) XXX_DiscardUnknown() {
	xxx_messageInfo_Institute.DiscardUnknown(m)
}

var xxx_messageInfo_Institute proto.InternalMessageInfo

func (m *Institute) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Institute) GetType() InstituteType {
	if m != nil {
		return m.Type
	}
	return InstituteType_INSTITUTE_TYPE_UNKNOWN
}

func (m *Institute) GetPriorCounsellingExperience() bool {
	if m != nil {
		return m.PriorCounsellingExperience
	}
	return false
}

func (m *Institute) GetPriorCounsellingExperienceInYears() int32 {
	if m != nil {
		return m.PriorCounsellingExperienceInYears
	}
	return 0
}

func (m *Institute) GetIsCertified() bool {
	if m != nil {
		return m.IsCertified
	}
	return false
}

func (m *Institute) GetCertificationType() string {
	if m != nil {
		return m.CertificationType
	}
	return ""
}

func (m *Institute) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type Occupation struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 OccupationType `protobuf:"varint,2,opt,name=type,proto3,enum=proto.OccupationType" json:"type,omitempty"`
	Name                 string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Occupation) Reset()         { *m = Occupation{} }
func (m *Occupation) String() string { return proto.CompactTextString(m) }
func (*Occupation) ProtoMessage()    {}
func (*Occupation) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{9}
}

func (m *Occupation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Occupation.Unmarshal(m, b)
}
func (m *Occupation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Occupation.Marshal(b, m, deterministic)
}
func (m *Occupation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Occupation.Merge(m, src)
}
func (m *Occupation) XXX_Size() int {
	return xxx_messageInfo_Occupation.Size(m)
}
func (m *Occupation) XXX_DiscardUnknown() {
	xxx_messageInfo_Occupation.DiscardUnknown(m)
}

var xxx_messageInfo_Occupation proto.InternalMessageInfo

func (m *Occupation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Occupation) GetType() OccupationType {
	if m != nil {
		return m.Type
	}
	return OccupationType_UNKNOWN
}

func (m *Occupation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.UserTypes", UserTypes_name, UserTypes_value)
	proto.RegisterEnum("proto.InstituteType", InstituteType_name, InstituteType_value)
	proto.RegisterEnum("proto.OccupationType", OccupationType_name, OccupationType_value)
	proto.RegisterType((*IdRequest)(nil), "proto.IdRequest")
	proto.RegisterType((*EmailRequest)(nil), "proto.EmailRequest")
	proto.RegisterType((*IdsRequest)(nil), "proto.IdsRequest")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*Address)(nil), "proto.Address")
	proto.RegisterType((*Location)(nil), "proto.Location")
	proto.RegisterType((*EducationQualification)(nil), "proto.EducationQualification")
	proto.RegisterType((*Institute)(nil), "proto.Institute")
	proto.RegisterType((*Occupation)(nil), "proto.Occupation")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 825 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0x5d, 0x73, 0xdb, 0x44,
	0x14, 0xad, 0xec, 0x38, 0xb6, 0xae, 0x5d, 0x57, 0xd9, 0x69, 0x33, 0x22, 0x7c, 0x19, 0x4d, 0x1f,
	0xdc, 0x40, 0xdb, 0x69, 0x18, 0x78, 0x62, 0x98, 0x71, 0xec, 0x6d, 0xba, 0x54, 0x91, 0xc3, 0x4a,
	0x2a, 0x13, 0x78, 0x30, 0x8a, 0xb4, 0x29, 0x3b, 0xc8, 0x92, 0xd0, 0xc7, 0x80, 0x79, 0xe0, 0x27,
	0xf0, 0xc6, 0xcf, 0xe2, 0x3f, 0x31, 0xbb, 0x5a, 0xf9, 0xa3, 0x6e, 0xe9, 0x93, 0xf7, 0xdc, 0x73,
	0x57, 0x7b, 0xcf, 0x3d, 0xf7, 0x8e, 0x61, 0x10, 0xa6, 0xcb, 0x65, 0x9a, 0x3c, 0xc9, 0xf2, 0xb4,
	0x4c, 0x51, 0x47, 0xfe, 0x58, 0x1f, 0x82, 0x4e, 0x22, 0xca, 0x7e, 0xab, 0x58, 0x51, 0xa2, 0x21,
	0xb4, 0x78, 0x64, 0x6a, 0x23, 0x6d, 0xac, 0xd3, 0x16, 0x8f, 0xac, 0x87, 0x30, 0xc0, 0xcb, 0x80,
	0xc7, 0x0d, 0x7f, 0x1f, 0x3a, 0x4c, 0x60, 0x95, 0x52, 0x03, 0xeb, 0x13, 0x00, 0x12, 0x15, 0x4d,
	0x8e, 0x01, 0x6d, 0x1e, 0x15, 0xa6, 0x36, 0x6a, 0x8f, 0x75, 0x2a, 0x8e, 0x56, 0x17, 0x3a, 0x78,
	0x99, 0x95, 0x2b, 0xeb, 0xef, 0x36, 0x1c, 0xf8, 0x05, 0xcb, 0xd1, 0x47, 0xa0, 0xdf, 0xf2, 0xbc,
	0x28, 0x9d, 0x60, 0xc9, 0xd4, 0xb7, 0x36, 0x01, 0x74, 0x02, 0xbd, 0x38, 0x50, 0x64, 0x4b, 0x92,
	0x6b, 0xbc, 0xa9, 0xa0, 0xbd, 0x55, 0x81, 0xb8, 0x91, 0x05, 0x45, 0xf1, 0x7b, 0x9a, 0x47, 0xe6,
	0x41, 0x7d, 0xa3, 0xc1, 0xe8, 0x18, 0x0e, 0x97, 0xe9, 0x0d, 0x8f, 0x99, 0xd9, 0x91, 0x8c, 0x42,
	0xe8, 0x11, 0x74, 0x83, 0x28, 0xca, 0x59, 0x51, 0x98, 0x87, 0x23, 0x6d, 0xdc, 0x3f, 0xbb, 0x57,
	0x37, 0xe6, 0x89, 0x9d, 0x86, 0x41, 0xc9, 0xd3, 0x84, 0x36, 0x3c, 0xfa, 0x02, 0x8e, 0xb2, 0x3c,
	0xbd, 0xe5, 0x31, 0xbb, 0xe2, 0x61, 0x59, 0xe5, 0xcc, 0xa7, 0xb6, 0xd9, 0x95, 0x5f, 0xdb, 0x27,
	0xd0, 0x43, 0x38, 0x28, 0x57, 0x19, 0x33, 0x7b, 0x23, 0x6d, 0x3c, 0x3c, 0x33, 0xd4, 0x57, 0x85,
	0x6e, 0x6f, 0x95, 0xb1, 0x82, 0x4a, 0x16, 0x3d, 0x03, 0x48, 0xc3, 0xb0, 0xca, 0xe4, 0x53, 0xa6,
	0x2e, 0x2b, 0x38, 0x52, 0xb9, 0xf3, 0x35, 0x41, 0xb7, 0x92, 0xd0, 0xd7, 0x70, 0xcc, 0xa2, 0xaa,
	0x2e, 0xee, 0xfb, 0x2a, 0x88, 0xf9, 0x2d, 0xaf, 0x81, 0x09, 0xb2, 0x96, 0x77, 0xb0, 0xc8, 0x84,
	0x2e, 0x2f, 0x5e, 0x05, 0x31, 0x8f, 0xcc, 0xfe, 0x48, 0x1b, 0xf7, 0x68, 0x03, 0xad, 0xbf, 0xa0,
	0x3b, 0x51, 0x1a, 0x2d, 0x18, 0x28, 0xb9, 0x36, 0x4f, 0xd8, 0x33, 0xe5, 0xca, 0x4e, 0xec, 0x8d,
	0x9c, 0x33, 0x65, 0xce, 0x4e, 0x0c, 0x7d, 0x0e, 0xbd, 0x58, 0x35, 0x50, 0x7a, 0xf4, 0x96, 0xbe,
	0xae, 0x13, 0xac, 0x9f, 0xa1, 0xd7, 0x44, 0x11, 0x82, 0x83, 0x90, 0x97, 0x2b, 0xf5, 0xb0, 0x3c,
	0x0b, 0xb7, 0x8b, 0x32, 0x28, 0x9b, 0x31, 0xa8, 0x81, 0xd0, 0x13, 0xa6, 0x55, 0x52, 0xe6, 0x2b,
	0x35, 0x05, 0x0d, 0x14, 0xb3, 0xf7, 0x27, 0xcf, 0xd4, 0x08, 0x88, 0xa3, 0xf5, 0x0d, 0x1c, 0xe3,
	0xb7, 0x77, 0xe5, 0x8d, 0x59, 0x17, 0xef, 0x27, 0x9b, 0x89, 0x93, 0x67, 0xeb, 0xdf, 0x16, 0xe8,
	0x24, 0x29, 0x4a, 0x5e, 0x56, 0x25, 0xdb, 0xbb, 0x31, 0x56, 0x46, 0xb7, 0xa4, 0xd1, 0xf7, 0x95,
	0xcc, 0x75, 0xbe, 0x70, 0x5b, 0x99, 0xfd, 0x2d, 0x9c, 0x64, 0x39, 0x4f, 0xf3, 0x69, 0x5a, 0x25,
	0x05, 0x8b, 0x63, 0x9e, 0xbc, 0xc6, 0x7f, 0x64, 0x2c, 0xe7, 0x2c, 0x09, 0x99, 0x14, 0xd1, 0xa3,
	0xff, 0x93, 0x81, 0x6c, 0xf8, 0xec, 0xdd, 0x2c, 0x49, 0xae, 0x59, 0x90, 0x17, 0x52, 0x75, 0x87,
	0xbe, 0x3f, 0x11, 0x8d, 0xa0, 0xcf, 0x8b, 0x29, 0xcb, 0x4b, 0x7e, 0xcb, 0x59, 0x24, 0xd7, 0xa2,
	0x47, 0xb7, 0x43, 0x62, 0xe0, 0xc3, 0x1a, 0xd4, 0xcd, 0x12, 0x52, 0xe4, 0x96, 0xe8, 0x74, 0x9f,
	0x40, 0xe3, 0xcd, 0x26, 0x75, 0xa5, 0xe3, 0x43, 0xd5, 0x0a, 0x35, 0x5b, 0xeb, 0x45, 0xb2, 0x7e,
	0x02, 0xd8, 0xcc, 0xf6, 0x5e, 0x3f, 0x1f, 0xed, 0xf4, 0xf3, 0xc1, 0xde, 0x32, 0x6c, 0x35, 0xb4,
	0x31, 0xab, 0xbd, 0x31, 0xeb, 0xf4, 0x2b, 0xd0, 0xd7, 0x4b, 0x86, 0xfa, 0xd0, 0xb5, 0xc9, 0xc5,
	0x0b, 0x0f, 0x53, 0xe3, 0x0e, 0x32, 0x60, 0x20, 0xc1, 0xc2, 0xc5, 0xf8, 0x25, 0xa6, 0x86, 0x86,
	0x74, 0xe8, 0x4c, 0x66, 0x97, 0xc4, 0x31, 0x5a, 0xa7, 0xff, 0x68, 0x70, 0x77, 0xc7, 0x33, 0x74,
	0x02, 0xc7, 0xc4, 0x71, 0x3d, 0xe2, 0xf9, 0x1e, 0x5e, 0x78, 0xd7, 0x57, 0x78, 0xe1, 0x3b, 0x2f,
	0x9d, 0xf9, 0x0f, 0x8e, 0x71, 0x07, 0x0d, 0x01, 0x88, 0x33, 0x23, 0xaf, 0xc8, 0xcc, 0x9f, 0xd8,
	0x86, 0x86, 0x3e, 0x80, 0x07, 0x78, 0xe6, 0x4f, 0x27, 0x1e, 0x99, 0x3b, 0x13, 0x7b, 0xb1, 0xbe,
	0x67, 0xb4, 0x04, 0x35, 0x9d, 0xfb, 0x8e, 0x8b, 0x6d, 0x9b, 0x38, 0x17, 0x5b, 0x54, 0x1b, 0x1d,
	0xc1, 0xdd, 0xe7, 0x73, 0x8a, 0xc9, 0x85, 0xb3, 0x70, 0x3d, 0x7f, 0x76, 0x6d, 0x1c, 0xa0, 0x7b,
	0xd0, 0x9f, 0x5d, 0x12, 0x6f, 0x31, 0xc5, 0x8e, 0x28, 0xba, 0x73, 0xba, 0x82, 0xe1, 0xae, 0x74,
	0xa1, 0x69, 0x53, 0x48, 0x1f, 0xba, 0xe2, 0x2a, 0x76, 0x3c, 0x43, 0x43, 0x03, 0xe8, 0x9d, 0xfb,
	0x2e, 0x71, 0xb0, 0xeb, 0x1a, 0x2d, 0x21, 0xd7, 0x9d, 0xd8, 0x13, 0x4a, 0xf0, 0x6c, 0xf1, 0xdd,
	0xfc, 0xbc, 0x7e, 0xcf, 0xc5, 0xf6, 0xf3, 0x05, 0xbe, 0xbc, 0xb2, 0xe7, 0xd7, 0x78, 0x56, 0xbf,
	0xe7, 0x3b, 0x9b, 0x40, 0x47, 0xb4, 0x64, 0xee, 0xbd, 0xc0, 0xd4, 0x38, 0x3c, 0xff, 0xf4, 0xc7,
	0x8f, 0x63, 0xfe, 0xfa, 0x97, 0xf2, 0x71, 0x95, 0x3d, 0xbe, 0x09, 0xc2, 0x5f, 0x59, 0x12, 0x3d,
	0xad, 0xff, 0x3b, 0x9e, 0x4a, 0x4f, 0x6e, 0x0e, 0xe5, 0xcf, 0x97, 0xff, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x8b, 0x6a, 0xf9, 0x45, 0x52, 0x06, 0x00, 0x00,
}
