// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lighter.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	proto1 "light-up-backend/common/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Lighter struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 *proto1.User         `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	LastLogin            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=lastLogin,proto3" json:"lastLogin,omitempty"`
	ModifiedOn           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=modifiedOn,proto3" json:"modifiedOn,omitempty"`
	CreatedOn            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	Verified             bool                 `protobuf:"varint,6,opt,name=verified,proto3" json:"verified,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Lighter) Reset()         { *m = Lighter{} }
func (m *Lighter) String() string { return proto.CompactTextString(m) }
func (*Lighter) ProtoMessage()    {}
func (*Lighter) Descriptor() ([]byte, []int) {
	return fileDescriptor_399daef8f04ebe2b, []int{0}
}

func (m *Lighter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lighter.Unmarshal(m, b)
}
func (m *Lighter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lighter.Marshal(b, m, deterministic)
}
func (m *Lighter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lighter.Merge(m, src)
}
func (m *Lighter) XXX_Size() int {
	return xxx_messageInfo_Lighter.Size(m)
}
func (m *Lighter) XXX_DiscardUnknown() {
	xxx_messageInfo_Lighter.DiscardUnknown(m)
}

var xxx_messageInfo_Lighter proto.InternalMessageInfo

func (m *Lighter) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Lighter) GetUser() *proto1.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Lighter) GetLastLogin() *timestamp.Timestamp {
	if m != nil {
		return m.LastLogin
	}
	return nil
}

func (m *Lighter) GetModifiedOn() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedOn
	}
	return nil
}

func (m *Lighter) GetCreatedOn() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedOn
	}
	return nil
}

func (m *Lighter) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

type LighterRequest struct {
	Lighter              *Lighter `protobuf:"bytes,1,opt,name=lighter,proto3" json:"lighter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LighterRequest) Reset()         { *m = LighterRequest{} }
func (m *LighterRequest) String() string { return proto.CompactTextString(m) }
func (*LighterRequest) ProtoMessage()    {}
func (*LighterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_399daef8f04ebe2b, []int{1}
}

func (m *LighterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LighterRequest.Unmarshal(m, b)
}
func (m *LighterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LighterRequest.Marshal(b, m, deterministic)
}
func (m *LighterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LighterRequest.Merge(m, src)
}
func (m *LighterRequest) XXX_Size() int {
	return xxx_messageInfo_LighterRequest.Size(m)
}
func (m *LighterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LighterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LighterRequest proto.InternalMessageInfo

func (m *LighterRequest) GetLighter() *Lighter {
	if m != nil {
		return m.Lighter
	}
	return nil
}

type LighterResponse struct {
	Lighter              *Lighter   `protobuf:"bytes,1,opt,name=lighter,proto3" json:"lighter,omitempty"`
	Lighters             []*Lighter `protobuf:"bytes,2,rep,name=lighters,proto3" json:"lighters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LighterResponse) Reset()         { *m = LighterResponse{} }
func (m *LighterResponse) String() string { return proto.CompactTextString(m) }
func (*LighterResponse) ProtoMessage()    {}
func (*LighterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_399daef8f04ebe2b, []int{2}
}

func (m *LighterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LighterResponse.Unmarshal(m, b)
}
func (m *LighterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LighterResponse.Marshal(b, m, deterministic)
}
func (m *LighterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LighterResponse.Merge(m, src)
}
func (m *LighterResponse) XXX_Size() int {
	return xxx_messageInfo_LighterResponse.Size(m)
}
func (m *LighterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LighterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LighterResponse proto.InternalMessageInfo

func (m *LighterResponse) GetLighter() *Lighter {
	if m != nil {
		return m.Lighter
	}
	return nil
}

func (m *LighterResponse) GetLighters() []*Lighter {
	if m != nil {
		return m.Lighters
	}
	return nil
}

func init() {
	proto.RegisterType((*Lighter)(nil), "proto.Lighter")
	proto.RegisterType((*LighterRequest)(nil), "proto.LighterRequest")
	proto.RegisterType((*LighterResponse)(nil), "proto.LighterResponse")
}

func init() { proto.RegisterFile("lighter.proto", fileDescriptor_399daef8f04ebe2b) }

var fileDescriptor_399daef8f04ebe2b = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x5d, 0xab, 0xd3, 0x40,
	0x10, 0x35, 0xe9, 0xfd, 0xe8, 0x9d, 0xdc, 0x1b, 0xbd, 0x7b, 0xa9, 0x84, 0xbc, 0x34, 0xe4, 0x41,
	0x82, 0xd0, 0x14, 0x2a, 0x82, 0x14, 0x41, 0x6d, 0x11, 0x29, 0x14, 0x84, 0xa8, 0x7d, 0xf0, 0x2d,
	0xcd, 0x6e, 0xe3, 0x62, 0x92, 0x8d, 0xd9, 0x4d, 0xa1, 0x7f, 0xc0, 0x5f, 0xe8, 0x0f, 0x92, 0xee,
	0x6e, 0xd2, 0x52, 0xc4, 0x58, 0x7c, 0xda, 0xcc, 0xcc, 0x39, 0x67, 0x66, 0xe7, 0x64, 0xe1, 0x2e,
	0xa3, 0xe9, 0x37, 0x41, 0xaa, 0xb0, 0xac, 0x98, 0x60, 0xe8, 0x52, 0x1e, 0xee, 0x6d, 0xc2, 0xf2,
	0x9c, 0x15, 0x2a, 0xe9, 0x0e, 0x53, 0xc6, 0xd2, 0x8c, 0x8c, 0x65, 0xb4, 0xae, 0x37, 0x63, 0x41,
	0x73, 0xc2, 0x45, 0x9c, 0x97, 0x0a, 0xe0, 0xff, 0x34, 0xe1, 0x7a, 0xa9, 0x74, 0x90, 0x0d, 0x26,
	0xc5, 0x8e, 0xe1, 0x19, 0xc1, 0x4d, 0x64, 0x52, 0x8c, 0x86, 0x70, 0x51, 0x73, 0x52, 0x39, 0xa6,
	0x67, 0x04, 0xd6, 0xc4, 0x52, 0x8c, 0xf0, 0x0b, 0x27, 0x55, 0x24, 0x0b, 0xe8, 0x15, 0xdc, 0x64,
	0x31, 0x17, 0x4b, 0x96, 0xd2, 0xc2, 0xe9, 0x49, 0x94, 0x1b, 0xaa, 0x8e, 0x61, 0xd3, 0x31, 0xfc,
	0xdc, 0x74, 0x8c, 0x0e, 0x60, 0x34, 0x05, 0xc8, 0x19, 0xa6, 0x1b, 0x4a, 0xf0, 0xc7, 0xc2, 0xb9,
	0xe8, 0xa4, 0x1e, 0xa1, 0xf7, 0x5d, 0x93, 0x8a, 0xc4, 0x42, 0x52, 0x2f, 0xbb, 0xbb, 0xb6, 0x60,
	0xe4, 0x42, 0x7f, 0x4b, 0x2a, 0xa9, 0xe3, 0x5c, 0x79, 0x46, 0xd0, 0x8f, 0xda, 0xd8, 0x9f, 0x82,
	0xad, 0xf7, 0x10, 0x91, 0x1f, 0x35, 0xe1, 0x02, 0x05, 0x70, 0xad, 0x37, 0x2c, 0x77, 0x62, 0x4d,
	0x6c, 0xbd, 0x81, 0x06, 0xd7, 0x94, 0xfd, 0x14, 0x1e, 0xb7, 0x5c, 0x5e, 0xb2, 0x82, 0x93, 0x7f,
	0x27, 0xa3, 0xe7, 0xd0, 0xd7, 0x9f, 0xdc, 0x31, 0xbd, 0xde, 0x1f, 0xa0, 0x6d, 0x7d, 0xf2, 0xab,
	0xd7, 0x4e, 0xf9, 0x89, 0x54, 0x5b, 0x9a, 0x10, 0xf4, 0x16, 0xee, 0xe6, 0xf2, 0x82, 0x8d, 0x8b,
	0x83, 0x13, 0xb6, 0xba, 0x8d, 0xfb, 0xf4, 0x34, 0xad, 0x06, 0xf5, 0x1f, 0xa1, 0xd7, 0x60, 0x7f,
	0x20, 0x42, 0xe7, 0x67, 0xbb, 0x05, 0x46, 0x4f, 0x34, 0x76, 0x81, 0xbb, 0xd9, 0x33, 0xb8, 0x3f,
	0x66, 0xbf, 0xcf, 0x63, 0x9a, 0xa1, 0x07, 0x0d, 0x97, 0x51, 0xb7, 0xc6, 0x4b, 0xb0, 0x0e, 0x1a,
	0x1c, 0xdd, 0xb6, 0xec, 0x52, 0xec, 0xfe, 0x42, 0x7b, 0x03, 0xf7, 0xab, 0xbd, 0x7d, 0x3b, 0x5d,
	0xda, 0xff, 0x99, 0x67, 0xcd, 0xfe, 0x0e, 0x1e, 0x56, 0x71, 0x46, 0xf1, 0x61, 0x7b, 0x67, 0x4b,
	0xcc, 0x61, 0xb0, 0x28, 0xfe, 0x53, 0x64, 0x16, 0x7c, 0x7d, 0x26, 0x2d, 0x1e, 0xd5, 0xe5, 0x68,
	0x1d, 0x27, 0xdf, 0x49, 0x81, 0xc7, 0xda, 0xf3, 0x11, 0x57, 0x3e, 0xeb, 0x17, 0x7c, 0x25, 0x8f,
	0x17, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb2, 0xf4, 0x6e, 0xf1, 0xfc, 0x03, 0x00, 0x00,
}
