// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lighter.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "light-up-backend/common/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Lighter struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string           `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string           `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string           `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string           `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Mobile               string           `protobuf:"bytes,6,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Country              string           `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	State                string           `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty"`
	City                 string           `protobuf:"bytes,9,opt,name=city,proto3" json:"city,omitempty"`
	Image                string           `protobuf:"bytes,10,opt,name=image,proto3" json:"image,omitempty"`
	IsActive             bool             `protobuf:"varint,11,opt,name=isActive,proto3" json:"isActive,omitempty"`
	Type                 proto1.UserTypes `protobuf:"varint,12,opt,name=type,proto3,enum=proto.UserTypes" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Lighter) Reset()         { *m = Lighter{} }
func (m *Lighter) String() string { return proto.CompactTextString(m) }
func (*Lighter) ProtoMessage()    {}
func (*Lighter) Descriptor() ([]byte, []int) {
	return fileDescriptor_399daef8f04ebe2b, []int{0}
}

func (m *Lighter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lighter.Unmarshal(m, b)
}
func (m *Lighter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lighter.Marshal(b, m, deterministic)
}
func (m *Lighter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lighter.Merge(m, src)
}
func (m *Lighter) XXX_Size() int {
	return xxx_messageInfo_Lighter.Size(m)
}
func (m *Lighter) XXX_DiscardUnknown() {
	xxx_messageInfo_Lighter.DiscardUnknown(m)
}

var xxx_messageInfo_Lighter proto.InternalMessageInfo

func (m *Lighter) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Lighter) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Lighter) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Lighter) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Lighter) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Lighter) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Lighter) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Lighter) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Lighter) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Lighter) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Lighter) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *Lighter) GetType() proto1.UserTypes {
	if m != nil {
		return m.Type
	}
	return proto1.UserTypes_LIGHTER
}

type CreateLighterRequest struct {
	Lighter              *Lighter `protobuf:"bytes,1,opt,name=lighter,proto3" json:"lighter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLighterRequest) Reset()         { *m = CreateLighterRequest{} }
func (m *CreateLighterRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLighterRequest) ProtoMessage()    {}
func (*CreateLighterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_399daef8f04ebe2b, []int{1}
}

func (m *CreateLighterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLighterRequest.Unmarshal(m, b)
}
func (m *CreateLighterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLighterRequest.Marshal(b, m, deterministic)
}
func (m *CreateLighterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLighterRequest.Merge(m, src)
}
func (m *CreateLighterRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLighterRequest.Size(m)
}
func (m *CreateLighterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLighterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLighterRequest proto.InternalMessageInfo

func (m *CreateLighterRequest) GetLighter() *Lighter {
	if m != nil {
		return m.Lighter
	}
	return nil
}

type LighterResponse struct {
	Lighter              *Lighter   `protobuf:"bytes,1,opt,name=lighter,proto3" json:"lighter,omitempty"`
	Lighters             []*Lighter `protobuf:"bytes,2,rep,name=lighters,proto3" json:"lighters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LighterResponse) Reset()         { *m = LighterResponse{} }
func (m *LighterResponse) String() string { return proto.CompactTextString(m) }
func (*LighterResponse) ProtoMessage()    {}
func (*LighterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_399daef8f04ebe2b, []int{2}
}

func (m *LighterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LighterResponse.Unmarshal(m, b)
}
func (m *LighterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LighterResponse.Marshal(b, m, deterministic)
}
func (m *LighterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LighterResponse.Merge(m, src)
}
func (m *LighterResponse) XXX_Size() int {
	return xxx_messageInfo_LighterResponse.Size(m)
}
func (m *LighterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LighterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LighterResponse proto.InternalMessageInfo

func (m *LighterResponse) GetLighter() *Lighter {
	if m != nil {
		return m.Lighter
	}
	return nil
}

func (m *LighterResponse) GetLighters() []*Lighter {
	if m != nil {
		return m.Lighters
	}
	return nil
}

func init() {
	proto.RegisterType((*Lighter)(nil), "proto.Lighter")
	proto.RegisterType((*CreateLighterRequest)(nil), "proto.CreateLighterRequest")
	proto.RegisterType((*LighterResponse)(nil), "proto.LighterResponse")
}

func init() { proto.RegisterFile("lighter.proto", fileDescriptor_399daef8f04ebe2b) }

var fileDescriptor_399daef8f04ebe2b = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0xa6, 0xd9, 0xfe, 0x4e, 0xbb, 0x01, 0x86, 0xd5, 0xca, 0x2a, 0x1c, 0xaa, 0x0a, 0xa1, 0x08,
	0xa9, 0xbb, 0x52, 0x11, 0x37, 0x0e, 0x50, 0x04, 0x68, 0x25, 0xc4, 0xa1, 0xc0, 0x85, 0x9b, 0x9b,
	0x0c, 0xc5, 0x22, 0x89, 0x83, 0xed, 0x2e, 0xca, 0x63, 0xf0, 0x38, 0xbc, 0x1d, 0xca, 0xd8, 0xc9,
	0x02, 0x5a, 0xb4, 0x9c, 0xec, 0xef, 0x6f, 0x3c, 0xf9, 0x14, 0x38, 0xce, 0xd5, 0xfe, 0x8b, 0x23,
	0x73, 0x56, 0x19, 0xed, 0x34, 0x0e, 0xf8, 0x98, 0xcf, 0x52, 0x5d, 0x14, 0xba, 0xf4, 0xe4, 0xf2,
	0x67, 0x04, 0xa3, 0xb7, 0xde, 0x86, 0x31, 0x44, 0x2a, 0x13, 0xbd, 0x45, 0x2f, 0x99, 0x6c, 0x23,
	0x95, 0xe1, 0x03, 0x98, 0x7c, 0x56, 0xc6, 0xba, 0x77, 0xb2, 0x20, 0x11, 0x31, 0x7d, 0x45, 0xe0,
	0x1c, 0xc6, 0xb9, 0x0c, 0xe2, 0x11, 0x8b, 0x1d, 0xc6, 0x13, 0x18, 0x50, 0x21, 0x55, 0x2e, 0xfa,
	0x2c, 0x78, 0xd0, 0x24, 0x2a, 0x69, 0xed, 0x77, 0x6d, 0x32, 0x31, 0xf0, 0x89, 0x16, 0xe3, 0x29,
	0x0c, 0x0b, 0xbd, 0x53, 0x39, 0x89, 0x21, 0x2b, 0x01, 0xa1, 0x80, 0x51, 0xaa, 0x0f, 0xa5, 0x33,
	0xb5, 0x18, 0xb1, 0xd0, 0xc2, 0xe6, 0x0d, 0xeb, 0xa4, 0x23, 0x31, 0xf6, 0x6f, 0x30, 0x40, 0x84,
	0x7e, 0xaa, 0x5c, 0x2d, 0x26, 0x4c, 0xf2, 0xbd, 0x71, 0xaa, 0x42, 0xee, 0x49, 0x80, 0x77, 0x32,
	0x68, 0xb6, 0x51, 0xf6, 0x45, 0xea, 0xd4, 0x25, 0x89, 0xe9, 0xa2, 0x97, 0x8c, 0xb7, 0x1d, 0xc6,
	0x87, 0xd0, 0x77, 0x75, 0x45, 0x62, 0xb6, 0xe8, 0x25, 0xf1, 0xfa, 0x8e, 0xef, 0xea, 0xec, 0xa3,
	0x25, 0xf3, 0xa1, 0xae, 0xc8, 0x6e, 0x59, 0x5d, 0x3e, 0x87, 0x93, 0x97, 0x86, 0xa4, 0xa3, 0x50,
	0xe0, 0x96, 0xbe, 0x1d, 0xc8, 0x3a, 0x4c, 0x60, 0x14, 0x9a, 0xe7, 0x32, 0xa7, 0xeb, 0x38, 0x0c,
	0x68, 0x7d, 0xad, 0xbc, 0xdc, 0xc3, 0xed, 0x2e, 0x6b, 0x2b, 0x5d, 0x5a, 0xfa, 0xff, 0x30, 0x3e,
	0x86, 0x71, 0xb8, 0x5a, 0x11, 0x2d, 0x8e, 0xae, 0xb1, 0x76, 0xfa, 0xfa, 0x47, 0x04, 0x71, 0x60,
	0xdf, 0x93, 0xb9, 0x54, 0x29, 0xe1, 0x6b, 0x38, 0xfe, 0x63, 0x7b, 0xbc, 0x1f, 0xd2, 0xd7, 0x7d,
	0xd3, 0xfc, 0xf4, 0xaf, 0xd1, 0x61, 0xdd, 0xe5, 0x2d, 0x7c, 0x06, 0xf1, 0x1b, 0x72, 0x81, 0xdf,
	0xd4, 0x17, 0x19, 0xb6, 0x7d, 0x5d, 0x64, 0x37, 0xa7, 0x37, 0x70, 0xf7, 0xf7, 0xf4, 0x2b, 0xfe,
	0x51, 0xee, 0x05, 0x3b, 0xa3, 0x9b, 0x67, 0x3c, 0x85, 0xe9, 0xd5, 0x0c, 0x8b, 0xb3, 0x2e, 0x5d,
	0xb9, 0xfa, 0xdf, 0xb1, 0x4d, 0xf2, 0xe9, 0x11, 0xf7, 0xb3, 0x3a, 0x54, 0xab, 0x9d, 0x4c, 0xbf,
	0x52, 0x99, 0x9d, 0x87, 0xc2, 0x56, 0xd6, 0x97, 0x74, 0xce, 0xd9, 0xdd, 0x90, 0x8f, 0x27, 0xbf,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x04, 0x4f, 0xf5, 0x51, 0x03, 0x00, 0x00,
}
