// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authentication.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "light-up-backend/common/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type TokenValidationRequest struct {
	Token                string             `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserType             []proto1.UserTypes `protobuf:"varint,2,rep,packed,name=userType,proto3,enum=proto.UserTypes" json:"userType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TokenValidationRequest) Reset()         { *m = TokenValidationRequest{} }
func (m *TokenValidationRequest) String() string { return proto.CompactTextString(m) }
func (*TokenValidationRequest) ProtoMessage()    {}
func (*TokenValidationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{2}
}

func (m *TokenValidationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenValidationRequest.Unmarshal(m, b)
}
func (m *TokenValidationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenValidationRequest.Marshal(b, m, deterministic)
}
func (m *TokenValidationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenValidationRequest.Merge(m, src)
}
func (m *TokenValidationRequest) XXX_Size() int {
	return xxx_messageInfo_TokenValidationRequest.Size(m)
}
func (m *TokenValidationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenValidationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenValidationRequest proto.InternalMessageInfo

func (m *TokenValidationRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *TokenValidationRequest) GetUserType() []proto1.UserTypes {
	if m != nil {
		return m.UserType
	}
	return nil
}

type TokenResponse struct {
	Result               *Token   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenResponse) Reset()         { *m = TokenResponse{} }
func (m *TokenResponse) String() string { return proto.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()    {}
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{3}
}

func (m *TokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenResponse.Unmarshal(m, b)
}
func (m *TokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenResponse.Marshal(b, m, deterministic)
}
func (m *TokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenResponse.Merge(m, src)
}
func (m *TokenResponse) XXX_Size() int {
	return xxx_messageInfo_TokenResponse.Size(m)
}
func (m *TokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenResponse proto.InternalMessageInfo

func (m *TokenResponse) GetResult() *Token {
	if m != nil {
		return m.Result
	}
	return nil
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{4}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Token) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{5}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "proto.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "proto.LoginResponse")
	proto.RegisterType((*TokenValidationRequest)(nil), "proto.TokenValidationRequest")
	proto.RegisterType((*TokenResponse)(nil), "proto.TokenResponse")
	proto.RegisterType((*Token)(nil), "proto.Token")
	proto.RegisterType((*Error)(nil), "proto.Error")
}

func init() { proto.RegisterFile("authentication.proto", fileDescriptor_d0dbc99083440df2) }

var fileDescriptor_d0dbc99083440df2 = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xd1, 0xab, 0xd3, 0x30,
	0x14, 0xc6, 0xef, 0xee, 0xb5, 0xd7, 0x79, 0xee, 0x26, 0x23, 0x56, 0x29, 0x03, 0x61, 0x04, 0x1f,
	0xf6, 0x60, 0x37, 0x98, 0xf8, 0x24, 0x32, 0x14, 0xf4, 0x69, 0x4f, 0xdd, 0x54, 0x10, 0x5f, 0xba,
	0xf6, 0xb0, 0x85, 0xb5, 0x4d, 0x4d, 0xd2, 0x89, 0x7f, 0xac, 0xff, 0x8b, 0xe4, 0x24, 0xab, 0x2d,
	0xea, 0xc3, 0x7d, 0x6a, 0xce, 0x97, 0xe4, 0xd7, 0x73, 0xbe, 0x2f, 0x10, 0xa6, 0x8d, 0x39, 0x62,
	0x65, 0x44, 0x96, 0x1a, 0x21, 0xab, 0x45, 0xad, 0xa4, 0x91, 0x2c, 0xa0, 0xcf, 0x74, 0x94, 0xc9,
	0xb2, 0xbc, 0x88, 0x7c, 0x07, 0xa3, 0x8d, 0x3c, 0x88, 0x2a, 0xc1, 0xef, 0x0d, 0x6a, 0xc3, 0x42,
	0x08, 0xb0, 0x4c, 0x45, 0x11, 0x0d, 0x66, 0x83, 0xf9, 0xa3, 0xc4, 0x15, 0x6c, 0x0a, 0xc3, 0x3a,
	0xd5, 0xfa, 0x87, 0x54, 0x79, 0x74, 0x4d, 0x1b, 0x6d, 0xcd, 0x18, 0x3c, 0x30, 0x3f, 0x6b, 0x8c,
	0x6e, 0x48, 0xa7, 0x35, 0x5f, 0xc3, 0xd8, 0x53, 0x75, 0x2d, 0x2b, 0x8d, 0x16, 0x6b, 0xe4, 0x09,
	0xab, 0x0b, 0x96, 0x0a, 0x16, 0xc1, 0xc3, 0x12, 0xb5, 0x4e, 0x0f, 0xe8, 0xa9, 0x97, 0x92, 0x7f,
	0x83, 0x67, 0x3b, 0x7b, 0xe4, 0x73, 0x5a, 0x88, 0x9c, 0x86, 0xe8, 0x34, 0xf8, 0x0f, 0xd2, 0x4b,
	0x18, 0x36, 0x1a, 0xd5, 0xce, 0x36, 0x72, 0x3d, 0xbb, 0x99, 0x3f, 0x5e, 0x4d, 0xdc, 0x80, 0x8b,
	0x4f, 0x5e, 0xd6, 0x49, 0x7b, 0x82, 0xbf, 0x86, 0x31, 0xd1, 0xdb, 0xf6, 0x5e, 0xc0, 0xad, 0x42,
	0xdd, 0x14, 0x86, 0xa8, 0x77, 0xab, 0x91, 0xbf, 0xec, 0x4e, 0xf9, 0x3d, 0xfe, 0x05, 0x02, 0x12,
	0xfe, 0xd3, 0x43, 0x08, 0xc1, 0xd9, 0xb6, 0x4b, 0xb3, 0x0c, 0x13, 0x57, 0x30, 0x0e, 0x01, 0x2a,
	0x25, 0x15, 0xf9, 0xf3, 0x87, 0xfc, 0xc1, 0x6a, 0x89, 0xdb, 0xe2, 0x6f, 0x21, 0xa0, 0xda, 0x7a,
	0x99, 0xc9, 0x1c, 0x89, 0x1b, 0x24, 0xb4, 0x66, 0x33, 0xb8, 0xcb, 0x51, 0x67, 0x4a, 0xd4, 0xd6,
	0x06, 0x6f, 0x54, 0x57, 0x5a, 0xfd, 0x1a, 0xc0, 0xd3, 0x77, 0xbd, 0xc4, 0xb7, 0xa8, 0xce, 0x22,
	0x43, 0xb6, 0x86, 0x09, 0xe5, 0xb0, 0x11, 0x87, 0xa3, 0xd9, 0x22, 0x9e, 0x50, 0xb1, 0x27, 0xbe,
	0x83, 0x6e, 0xec, 0xd3, 0xb0, 0x2f, 0x3a, 0x5b, 0xf8, 0x15, 0x7b, 0xe3, 0x9f, 0x07, 0x01, 0xee,
	0x7b, 0xf9, 0x23, 0x8c, 0x7d, 0x7e, 0xe8, 0x7c, 0x7b, 0xde, 0xb5, 0xf5, 0xaf, 0x68, 0x5b, 0x4e,
	0x2f, 0x1b, 0x7e, 0xf5, 0x7e, 0xf9, 0x35, 0x2e, 0xec, 0xff, 0xe3, 0xa6, 0x8e, 0xf7, 0x69, 0x76,
	0xc2, 0x2a, 0x5f, 0xf6, 0x5f, 0x78, 0xac, 0xdd, 0xc0, 0x4b, 0x02, 0xec, 0x6f, 0xe9, 0xf3, 0xea,
	0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x27, 0x07, 0x9d, 0xac, 0x08, 0x03, 0x00, 0x00,
}
